# Generated by Django 5.2.7 on 2026-05-06 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Programs', '0001_initial'),
        ('accounts', '0001_initial'),
        ('admissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique code e.g., TUITION_FEE', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Fee name', max_length=100)),
                ('category', models.CharField(choices=[('application', 'Application'), ('tuition', 'Tuition'), ('registration', 'Registration'), ('retake', 'Retake / resit'), ('exam', 'Examination'), ('service', 'Service / administrative'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fee Head',
                'verbose_name_plural': 'Fee Heads',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(max_length=100)),
                ('nationality_type', models.CharField(max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=50)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_level', models.ManyToManyField(to='admissions.academiclevel')),
                ('admission_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.batch')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_reference', models.CharField(max_length=50, unique=True)),
                ('payment_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('fee_type', models.CharField(default='Application Fees', max_length=40)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='admissions.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('application', 'Application fees'), ('tuition', 'Tuition'), ('general', 'General / service fees')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('term', models.CharField(blank=True, default='', max_length=50)),
                ('scope', models.CharField(choices=[('program', 'Program'), ('intake', 'Intake/Batch'), ('class', 'Class'), ('term', 'Term/Semester')], default='intake', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('inactive', 'Inactive')], default='draft', max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('nationality_type', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_levels', models.ManyToManyField(blank=True, related_name='fee_plans', to='admissions.academiclevel')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_plans', to='admissions.batch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fee_plans', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_plans', to='Programs.program')),
                ('programs', models.ManyToManyField(blank=True, related_name='fee_plan_programs', to='Programs.program')),
            ],
            options={
                'verbose_name': 'Fee Plan',
                'verbose_name_plural': 'Fee Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeePlanRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_stage', models.CharField(choices=[('form_submission', 'On Form Submission'), ('admission_approved', 'On Admission Approval'), ('semester_start', 'On Semester Start'), ('course_enrollment', 'On Course Enrollment'), ('course_retake', 'Course retake / resit')], default='form_submission', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('amount_international', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency_international', models.CharField(blank=True, default='', max_length=3)),
                ('installment_number', models.PositiveIntegerField(blank=True, null=True)),
                ('due_date_days', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.campus')),
                ('course_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_plan_rules', to='Programs.courseunit')),
                ('fee_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='payments.feehead')),
                ('fee_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='payments.feeplan')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Programs.program')),
                ('program_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Programs.programbatch')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Programs.semester')),
            ],
            options={
                'verbose_name': 'Fee Plan Rule',
                'verbose_name_plural': 'Fee Plan Rules',
                'ordering': ['fee_plan', 'order', 'installment_number'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_tuition_payment_percentage', models.DecimalField(decimal_places=2, default=50.0, help_text='Minimum % of semester tuition that must be paid before course registration', max_digits=5)),
                ('registration_start_date', models.DateTimeField(blank=True, null=True)),
                ('registration_end_date', models.DateTimeField(blank=True, null=True)),
                ('require_admission_approval', models.BooleanField(default=True)),
                ('require_enrollment', models.BooleanField(default=True, help_text='Require student to have an admission intake batch assigned (legacy gate).')),
                ('require_programme_enrollment', models.BooleanField(default=True, help_text="Require student to have an active StudentProgrammeEnrollment (status='enrolled', i.e. commitment fee confirmed). This is the main academic enrollment gate.")),
                ('skip_tuition_check', models.BooleanField(default=False, help_text='When True, the minimum tuition payment percentage threshold is skipped entirely. Students can register regardless of how much tuition they have paid.')),
                ('is_active', models.BooleanField(default=True, help_text='Master switch for course registration')),
                ('auto_enroll_on_admission', models.BooleanField(default=False, help_text='When enabled, students are automatically academically enrolled on admission (skips commitment fee gate).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_registration_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registration Settings',
                'verbose_name_plural': 'Registration Settings',
            },
        ),
        migrations.CreateModel(
            name='StudentTuitionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('scheduled', 'Scheduled (semester fee)'), ('ad_hoc', 'Ad-hoc (individual charge)')], default='scheduled', max_length=10)),
                ('label', models.CharField(blank=True, help_text="Human-readable description e.g. 'Late registration penalty – Sem 2 2025'", max_length=200)),
                ('is_waived', models.BooleanField(default=False, help_text='Soft-cancel: charge exists but is not owed.')),
                ('waived_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('payment_method', models.CharField(blank=True, choices=[('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('other', 'Other')], default='', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('receipt_number', models.CharField(blank=True, max_length=100)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charged_by', models.ForeignKey(blank=True, help_text='Staff member who created this ad-hoc charge.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_charges', to=settings.AUTH_USER_MODEL)),
                ('fee_head', models.ForeignKey(blank=True, help_text='For ad-hoc charges: the fee category (retake, service, etc.). NULL for scheduled.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_hoc_payments', to='payments.feehead')),
                ('fee_plan_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_payments', to='payments.feeplanrule')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuition_payments', to='Programs.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuition_payments', to='admissions.admittedstudent')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_tuition_payments', to=settings.AUTH_USER_MODEL)),
                ('waived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waived_charges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Tuition Payment',
                'verbose_name_plural': 'Student Tuition Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
