# Generated by Django 5.2.7 on 2025-11-17 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0017_alter_application_study_mode'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(max_length=100)),
                ('nationality_type', models.CharField(choices=[('local', 'Local'), ('international', 'International')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_level', models.ManyToManyField(to='admissions.academiclevel')),
                ('admission_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.batch')),
            ],
            options={
                'unique_together': {('nationality_type', 'admission_period')},
            },
        ),
    ]
