# Generated by Django 5.2.5 on 2026-05-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feeplanrule",
            name="payable_term_number",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Term within payable_year_of_study (1-based).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="feeplanrule",
            name="payable_year_of_study",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="When set with payable_term_number, fee is due at this curriculum year/term.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="feeplan",
            name="plan_type",
            field=models.CharField(
                choices=[
                    ("application", "Application fees"),
                    ("tuition", "Tuition"),
                    ("general", "General / service fees"),
                    ("other_schedule", "Scheduled other fees (year/term milestones)"),
                ],
                max_length=20,
            ),
        ),
    ]
