# Generated by Django 5.2.7 on 2026-05-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_other_fee_schedule_milestone_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeplanrule',
            name='payable_term_number',
        ),
        migrations.RemoveField(
            model_name='feeplanrule',
            name='payable_year_of_study',
        ),
        migrations.AlterField(
            model_name='feeplan',
            name='plan_type',
            field=models.CharField(choices=[('application', 'Application fees'), ('tuition', 'Tuition'), ('general', 'General / service fees')], max_length=20),
        ),
    ]
