# Generated by Django 5.2.7 on 2025-11-18 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_applicationfee'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicationfee',
            unique_together=set(),
        ),
    ]
