# Generated by Django 5.2.7 on 2026-05-13 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0021_merge_20260514_0211'),
        ('payments', '0002_other_fee_schedule_milestone_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeplanrule',
            name='payable_term_number',
        ),
        migrations.RemoveField(
            model_name='feeplanrule',
            name='payable_year_of_study',
        ),
        migrations.AlterField(
            model_name='feeplan',
            name='plan_type',
            field=models.CharField(choices=[('application', 'Application fees'), ('tuition', 'Tuition'), ('general', 'General / service fees')], max_length=20),
        ),
        migrations.CreateModel(
            name='TuitionLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date_time', models.DateTimeField()),
                ('schoolpay_receipt_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('settlement_bank_code', models.CharField(max_length=50)),
                ('source_channel_trans_detail', models.TextField(blank=True)),
                ('source_channel_transaction_id', models.CharField(db_index=True, max_length=100)),
                ('source_payment_channel', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=255)),
                ('student_payment_code', models.CharField(db_index=True, max_length=100)),
                ('student_registration_number', models.CharField(blank=True, max_length=100)),
                ('transaction_completion_status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Failed', 'Failed'), ('Reversed', 'Reversed')], max_length=20)),
                ('raw_response', models.JSONField(default=dict)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('reconciled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuition_ledgers', to='admissions.admittedstudent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date_time'],
                'indexes': [models.Index(fields=['student_payment_code'], name='payments_tu_student_5956f8_idx'), models.Index(fields=['schoolpay_receipt_number'], name='payments_tu_schoolp_3952ca_idx')],
            },
        ),
    ]
