# Generated by Django 5.2.7 on 2025-11-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_applicationfee_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationfee',
            name='nationality_type',
            field=models.CharField(max_length=20),
        ),
    ]
