# Generated by Django 5.2.7 on 2026-05-13 21:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0020_admittedstudent_admissions__student_ea9b04_idx'),
        ('payments', '0003_remove_feeplanrule_payable_term_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tuitionledger',
            index=models.Index(fields=['student_payment_code'], name='payments_tu_student_5956f8_idx'),
        ),
        migrations.AddIndex(
            model_name='tuitionledger',
            index=models.Index(fields=['schoolpay_receipt_number'], name='payments_tu_schoolp_3952ca_idx'),
        ),
    ]
