# Generated by Django 5.2.7 on 2026-05-14 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_feeplanrule_payable_term_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitionledger',
            name='settlement_bank_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
