# Generated by Django 5.2.7 on 2026-03-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_applicationpayment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationpayment',
            name='fee_type',
            field=models.CharField(default='Application Fees', max_length=20),
        ),
    ]
