# Generated by Django 5.2.7 on 2026-03-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_applicationpayment_fee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationfee',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name='applicationfee',
            name='nationality_type',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='applicationpayment',
            name='fee_type',
            field=models.CharField(default='Application Fees', max_length=40),
        ),
    ]
