# Generated by Django 5.2.7 on 2026-07-24 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0050_admitted_bonafide_list_idx"),
        ("payments", "0010_bursar_weekly_report"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentFeeExemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payable_year_of_study",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="If set, only this curriculum year. Blank = all years.",
                        null=True,
                    ),
                ),
                (
                    "payable_term_number",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="If set, only this term (requires year). Blank = all terms in scope.",
                        null=True,
                    ),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_fee_exemptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fee_head",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_exemptions",
                        to="payments.feehead",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revoked_fee_exemptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_exemptions",
                        to="admissions.admittedstudent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student fee exemption",
                "verbose_name_plural": "Student fee exemptions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "is_active"],
                        name="payments_st_student_83a147_idx",
                    ),
                    models.Index(
                        fields=["fee_head", "is_active"],
                        name="payments_st_fee_hea_a8ebb4_idx",
                    ),
                ],
            },
        ),
    ]
