# Generated by Django 5.2.7 on 2026-07-31 17:52
#
# Parallel history: 0015 also renamed the same index. On DBs that already applied
# 0015 (or never had payments_ma_status_7a0b1c_idx), RenameIndex fails with:
#   OperationalError: no such index: payments_ma_status_7a0b1c_idx
# Update Django state only for the rename; AlterField still runs on the DB.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0012_manual_bank_payment_change_request"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameIndex(
                    model_name="manualbankpaymentchangerequest",
                    new_name="payments_ma_status_b6f60e_idx",
                    old_name="payments_ma_status_7a0b1c_idx",
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name="registrationsettings",
            name="min_tuition_payment_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=50.0,
                help_text=(
                    "Minimum % of current-semester billed fees (tuition + functional / "
                    "other scheduled charges) that must be paid before course registration"
                ),
                max_digits=5,
            ),
        ),
    ]
