# Generated by Django 5.2.5 on 2026-07-31 10:30
#
# This migration originally duplicated 0013_rename_payments_ma_status_…:
# RenameIndex 7a0b1c → b6f60e + AlterField on RegistrationSettings.
# On databases that already applied 0013_rename, re-running RenameIndex fails with:
#   ValueError: No index named payments_ma_status_7a0b1c_idx …
# Keep the migration node for the merge graph, but do nothing.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0014_tuitionledger_status_indexes"),
    ]

    operations = []
