# Generated by Django 5.2.5 on 2026-07-31 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0014_tuitionledger_status_indexes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="manualbankpaymentchangerequest",
            new_name="payments_ma_status_b6f60e_idx",
            old_name="payments_ma_status_7a0b1c_idx",
        ),
        migrations.AlterField(
            model_name="registrationsettings",
            name="min_tuition_payment_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=50.0,
                help_text="Minimum % of current-semester billed fees (tuition + functional / other scheduled charges) that must be paid before course registration",
                max_digits=5,
            ),
        ),
    ]
