# Generated by Django 5.2.7 on 2026-08-05 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_rename_payments_ma_status_7a0b1c_idx_payments_ma_status_b6f60e_idx_and_more'),
        ('payments', '0015_rename_payments_ma_status_7a0b1c_idx_payments_ma_status_b6f60e_idx_and_more'),
    ]

    operations = [
    ]
