# Generated by Django 5.2.7 on 2026-09-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_exemption_form_fee_payment_proxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationsettings',
            name='auto_enroll_on_admission',
            field=models.BooleanField(default=False, help_text='When enabled, admitted students are academically enrolled (SPE status=enrolled) immediately on admission without waiting for the commitment fee. Turning this ON also backfills existing admitted students who are still pending / missing SPE. Course registration still uses the tuition % and other gates below.'),
        ),
    ]
