# Generated by Django 5.2.5 on 2026-09-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0019_alter_registrationsettings_auto_enroll_on_admission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feehead",
            name="code",
            field=models.CharField(
                help_text="Unique code e.g., TUITION_FEE", max_length=40, unique=True
            ),
        ),
    ]
