# Generated by Django 5.2.5 on 2026-07-07 11:44

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LeaveAccrual",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("accrual_date", models.DateField()),
                ("days_accrued", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("ANNUAL_GRANT", "Annual Entitlement Grant"),
                            ("MONTHLY_ACCRUAL", "Monthly Accrual"),
                            ("CARRY_FORWARD", "Carry Forward from Previous Year"),
                            ("ADJUSTMENT", "Manual HR Adjustment"),
                            ("ENCASHMENT", "Leave Encashment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-accrual_date", "staff"],
            },
        ),
        migrations.CreateModel(
            name="LeaveApproval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "level",
                    models.IntegerField(help_text="Approval sequence (1, 2, 3...)"),
                ),
                (
                    "approver_role",
                    models.CharField(
                        choices=[
                            ("SUPERVISOR", "Supervisor/Team Leader"),
                            ("DIRECTOR", "Director/Head of Department"),
                            ("DVC", "Deputy Vice Chancellor"),
                            ("HR_ADMIN", "HR Administrator"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("SKIPPED", "Skipped (No Supervisor)"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("decision_date", models.DateTimeField(blank=True, null=True)),
                ("comments", models.TextField(blank=True)),
                (
                    "is_current",
                    models.BooleanField(
                        default=False, help_text="Is this the current pending level?"
                    ),
                ),
                (
                    "is_appeal_review",
                    models.BooleanField(
                        default=False, help_text="Is this an appeal review?"
                    ),
                ),
            ],
            options={
                "ordering": ["leave_request", "level"],
            },
        ),
        migrations.CreateModel(
            name="LeaveBalance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "total_entitled",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Total days entitled for the year",
                        max_digits=6,
                    ),
                ),
                (
                    "carried_over",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Days carried from previous year",
                        max_digits=6,
                    ),
                ),
                (
                    "carried_expiry_date",
                    models.DateField(
                        blank=True, help_text="When carried days expire", null=True
                    ),
                ),
                (
                    "earned_this_year",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Days accrued so far this year",
                        max_digits=6,
                    ),
                ),
                (
                    "adjustments",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Manual HR adjustments (+/-)",
                        max_digits=6,
                    ),
                ),
                (
                    "taken",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Days already taken (approved leaves)",
                        max_digits=6,
                    ),
                ),
                (
                    "pending",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Days in pending requests",
                        max_digits=6,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-year", "staff", "leave_type"],
            },
        ),
        migrations.CreateModel(
            name="LeavePolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "position_category",
                    models.CharField(
                        choices=[
                            ("ALL", "All Positions"),
                            ("ACADEMIC", "Academic Staff"),
                            ("ADMINISTRATIVE", "Administrative Staff"),
                            ("SUPPORT", "Support Staff"),
                        ],
                        default="ALL",
                        max_length=20,
                    ),
                ),
                (
                    "annual_entitlement_days",
                    models.DecimalField(
                        decimal_places=2,
                        default=21.0,
                        help_text="Days per year",
                        max_digits=5,
                    ),
                ),
                (
                    "accrual_method",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Monthly Accrual"),
                            ("ANNUAL", "Annual Lump Sum"),
                            ("PRORATED", "Pro-rated on Hire"),
                        ],
                        default="MONTHLY",
                        max_length=10,
                    ),
                ),
                (
                    "min_notice_days",
                    models.IntegerField(
                        default=3, help_text="Days advance notice required"
                    ),
                ),
                (
                    "max_consecutive_days",
                    models.IntegerField(
                        default=30, help_text="Maximum consecutive days allowed"
                    ),
                ),
                ("effective_date", models.DateField(default=django.utils.timezone.now)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["campus", "leave_type"],
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "request_number",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated: LV-2026-0001",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "total_days",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Calculated working days",
                        max_digits=5,
                    ),
                ),
                ("reason", models.TextField(help_text="Reason for leave request")),
                (
                    "contact_during_leave",
                    models.CharField(
                        blank=True,
                        help_text="Phone/email for emergencies",
                        max_length=200,
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="Medical certificate, etc.",
                        null=True,
                        upload_to="leave/attachments/%Y/%m/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("UNDER_APPEAL", "Under Appeal"),
                            ("APPEAL_REJECTED", "Appeal Rejected"),
                            ("CANCELLED", "Cancelled by Staff"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("request_date", models.DateTimeField(auto_now_add=True)),
                ("supervisor_comment", models.TextField(blank=True)),
                ("hr_comment", models.TextField(blank=True)),
                ("can_appeal", models.BooleanField(default=False)),
                ("appeal_reason", models.TextField(blank=True)),
                ("appeal_date", models.DateTimeField(blank=True, null=True)),
                (
                    "appeal_deadline",
                    models.DateField(
                        blank=True,
                        help_text="Deadline to file appeal (3 days after rejection)",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-request_date"],
            },
        ),
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Short code (e.g., ANN, SCK)",
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "max_days_per_year",
                    models.IntegerField(
                        default=21, help_text="Maximum days allowed per year"
                    ),
                ),
                (
                    "requires_document",
                    models.BooleanField(
                        default=False,
                        help_text="Requires supporting document (medical cert, etc.)",
                    ),
                ),
                ("is_paid", models.BooleanField(default=True)),
                (
                    "gender_specific",
                    models.CharField(
                        choices=[
                            ("ALL", "All Genders"),
                            ("MALE", "Male Only"),
                            ("FEMALE", "Female Only"),
                        ],
                        default="ALL",
                        max_length=10,
                    ),
                ),
                (
                    "has_accrual",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this leave type accrues monthly",
                    ),
                ),
                ("carry_over_allowed", models.BooleanField(default=True)),
                (
                    "max_carry_over_days",
                    models.IntegerField(
                        default=10, help_text="Maximum days that can carry to next year"
                    ),
                ),
                (
                    "carry_over_expiry_months",
                    models.IntegerField(
                        default=6, help_text="Months until carried leave expires"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3498db",
                        help_text="Hex color for calendar display",
                        max_length=7,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PublicHoliday",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("date", models.DateField()),
                (
                    "is_recurring",
                    models.BooleanField(default=True, help_text="Repeats every year?"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
    ]
