# Generated by Django 5.2.5 on 2026-07-07 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0040_ar_data_clerk_role"),
        ("leave", "0001_initial"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaveaccrual",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_accruals",
                to="staff.staffprofile",
            ),
        ),
        migrations.AddField(
            model_name="leaveapproval",
            name="approver",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific person or null for any HR",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_approvals",
                to="staff.staffprofile",
            ),
        ),
        migrations.AddField(
            model_name="leavebalance",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_balances",
                to="staff.staffprofile",
            ),
        ),
        migrations.AddField(
            model_name="leavepolicy",
            name="campus",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave blank for global policy",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.campus",
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_requests",
                to="staff.staffprofile",
            ),
        ),
        migrations.AddField(
            model_name="leaveapproval",
            name="leave_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approvals",
                to="leave.leaverequest",
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="leave_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="leave.leavetype"
            ),
        ),
        migrations.AddField(
            model_name="leavepolicy",
            name="leave_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="leave.leavetype"
            ),
        ),
        migrations.AddField(
            model_name="leavebalance",
            name="leave_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="leave.leavetype"
            ),
        ),
        migrations.AddField(
            model_name="leaveaccrual",
            name="leave_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="leave.leavetype"
            ),
        ),
        migrations.AddField(
            model_name="publicholiday",
            name="campus",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave blank for all campuses",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.campus",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="leaveapproval",
            unique_together={("leave_request", "level")},
        ),
        migrations.AlterUniqueTogether(
            name="leavepolicy",
            unique_together={("campus", "leave_type", "position_category")},
        ),
        migrations.AlterUniqueTogether(
            name="leavebalance",
            unique_together={("staff", "leave_type", "year")},
        ),
    ]
