# Generated by Django 5.2.7 on 2026-03-27 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionReports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customisedadmissionreportspermissions',
            options={'permissions': [('view_admissionreports', 'Can view Admission Reports'), ('view_setup', 'Can View Academic Setup')]},
        ),
    ]
