# Generated by Django 5.2.5 on 2026-07-07 11:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0040_ar_data_clerk_role"),
        ("hiring", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkUploadStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_path", models.FileField(upload_to="bulk_uploads/")),
                ("status", models.CharField(default="pending", max_length=20)),
                ("total_records", models.IntegerField(default=0)),
                ("processed_records", models.IntegerField(default=0)),
                ("success_records", models.IntegerField(default=0)),
                ("failed_records", models.IntegerField(default=0)),
                ("error_log", models.TextField(blank=True, null=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("code", models.CharField(max_length=10)),
                (
                    "description",
                    models.TextField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PositonLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StaffType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DepartmentTeams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(max_length=20)),
                (
                    "description",
                    models.TextField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="staff.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_supervisor", models.BooleanField(default=False)),
                ("is_hr", models.BooleanField(default=False)),
                ("is_director", models.BooleanField(default=False)),
                ("staff_no", models.CharField(blank=True, max_length=50, unique=True)),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                (
                    "nssf_no",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="NSSF Number"
                    ),
                ),
                (
                    "tin_no",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="TIN Number"
                    ),
                ),
                (
                    "university_email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                (
                    "personal_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "passport_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="staff_photos/%Y/"
                    ),
                ),
                ("job_title", models.CharField(blank=True, max_length=20, null=True)),
                ("system_login", models.BooleanField(default=False)),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hiring.jobapplication",
                    ),
                ),
                (
                    "campus",
                    models.ManyToManyField(
                        related_name="staff_profiles", to="accounts.campus"
                    ),
                ),
                (
                    "managed_org_units",
                    models.ManyToManyField(
                        blank=True, related_name="managed_by", to="staff.department"
                    ),
                ),
                (
                    "org_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_members",
                        to="staff.department",
                    ),
                ),
                (
                    "position_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="staff.positonlevel",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="staff.departmentteams",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="staff.stafftype",
                    ),
                ),
            ],
            options={
                "ordering": ["staff_no"],
            },
        ),
        migrations.CreateModel(
            name="StaffContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("PERMANENT", "Permanent Contract"),
                            ("FIXED_TERM", "Fixed Term Contract"),
                            ("TEMPORARY", "Temporary Contract"),
                            ("PROBATION", "Probation Period"),
                            ("CONSULTANT", "Consultant Agreement"),
                            ("PART_TIME", "Part-Time Contract"),
                        ],
                        help_text="Type of employment contract",
                        max_length=20,
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(
                        help_text="Unique contract reference number",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("start_date", models.DateField(help_text="Contract start date")),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Contract end date (leave blank for permanent contracts)",
                        null=True,
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        help_text="Position/title as per contract", max_length=200
                    ),
                ),
                (
                    "salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Annual salary (optional, confidential)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "contract_file",
                    models.FileField(
                        help_text="Upload signed contract document (PDF, DOC, DOCX)",
                        upload_to="contracts/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "doc", "docx"]
                            )
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("EXPIRED", "Expired"),
                            ("TERMINATED", "Terminated"),
                            ("RENEWED", "Renewed"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes or special terms"
                    ),
                ),
                (
                    "alert_sent_30_days",
                    models.BooleanField(
                        default=False, help_text="Alert sent 30 days before expiry"
                    ),
                ),
                (
                    "alert_sent_60_days",
                    models.BooleanField(
                        default=False, help_text="Alert sent 60 days before expiry"
                    ),
                ),
                (
                    "alert_sent_90_days",
                    models.BooleanField(
                        default=False, help_text="Alert sent 90 days before expiry"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        help_text="Department as specified in contract",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="staff.department",
                    ),
                ),
                (
                    "renewal_of",
                    models.ForeignKey(
                        blank=True,
                        help_text="If this is a renewal, link to previous contract",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="renewals",
                        to="staff.staffcontract",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        help_text="Staff member this contract belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="staff.staffprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Contract",
                "verbose_name_plural": "Staff Contracts",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="SystemPermissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="staff.staffprofile",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("view_team_appraisals", "Can view team appraisals"),
                    ("view_all_appraisals", "Can view all appraisals (HR)"),
                    ("manage_staff", "Can manage staff"),
                    ("view_pips", "Can view pips"),
                    ("request_leave", "Can request leave"),
                    ("view_supervisedstaff", "Can view supervised staff"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SupervisionAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "staff_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_supervisors",
                        to="staff.staffprofile",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervision_assignments",
                        to="staff.staffprofile",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asigned_teams",
                        to="staff.departmentteams",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("staff_member__isnull", True), ("team__isnull", False)
                            ),
                            models.Q(
                                ("staff_member__isnull", False), ("team__isnull", True)
                            ),
                            _connector="OR",
                        ),
                        name="one_supervision_target",
                    )
                ],
            },
        ),
    ]
