# Generated by Django 5.2.7 on 2026-08-19 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_staff_id_cards'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='staffidcard',
            new_name='staff_staff_staff_p_500d18_idx',
            old_name='staff_staff_staff_p_8c1a2f_idx',
        ),
        migrations.RenameIndex(
            model_name='staffidcard',
            new_name='staff_staff_status_00d9a9_idx',
            old_name='staff_staff_status_9d4b11_idx',
        ),
    ]
