# Generated by Django 5.2.5 on 2026-08-03 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0045_hostel_module_initial"),
        ("admissions", "0055_seed_hod_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=64)),
                ("name", models.CharField(max_length=200)),
                (
                    "external_block_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Original Excel BuildingID (e.g. Block-I)",
                        max_length=64,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["hostel__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="Floor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=64)),
                ("name", models.CharField(max_length=100)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="floors",
                        to="hostel.building",
                    ),
                ),
            ],
            options={
                "ordering": ["building__name", "sort_order", "name"],
                "unique_together": {("building", "code")},
            },
        ),
        migrations.CreateModel(
            name="Hostel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=64)),
                ("name", models.CharField(max_length=200)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("mixed", "Mixed"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hostels",
                        to="accounts.campus",
                    ),
                ),
            ],
            options={
                "ordering": ["campus__name", "name"],
                "permissions": [
                    (
                        "manage_hostel_inventory",
                        "Can manage hostel inventory (halls, rooms, beds)",
                    ),
                    ("assign_hostel", "Can assign students to hostel beds"),
                    ("end_hostel_allocation", "Can end or cancel hostel allocations"),
                    (
                        "view_hostel_reports",
                        "Can view hostel occupancy and finance-ops reports",
                    ),
                ],
                "unique_together": {("campus", "code")},
            },
        ),
        migrations.AddField(
            model_name="building",
            name="hostel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buildings",
                to="hostel.hostel",
            ),
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=64, unique=True)),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "room_kind",
                    models.CharField(
                        choices=[
                            ("bedroom", "Bedroom"),
                            ("store", "Store"),
                            ("common", "Common room"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="bedroom",
                        max_length=16,
                    ),
                ),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Bed count for bedrooms; 0 for non-bedroom spaces.",
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=200)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "floor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="hostel.floor",
                    ),
                ),
            ],
            options={
                "ordering": ["floor__building__name", "floor__sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="Bed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("occupied", "Occupied"),
                            ("blocked", "Blocked"),
                            ("maintenance", "Maintenance"),
                        ],
                        db_index=True,
                        default="available",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beds",
                        to="hostel.room",
                    ),
                ),
            ],
            options={
                "ordering": ["room__code", "label"],
                "unique_together": {("room", "label")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="building",
            unique_together={("hostel", "code")},
        ),
        migrations.CreateModel(
            name="HostelAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        db_index=True, help_text="e.g. 2025/2026", max_length=32
                    ),
                ),
                ("term_number", models.PositiveSmallIntegerField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("ended", "Ended"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=16,
                    ),
                ),
                ("check_in", models.DateField(blank=True, null=True)),
                ("check_out", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hostel_allocations_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="hostel.bed",
                    ),
                ),
                (
                    "ended_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hostel_allocations_ended",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hostel_allocations",
                        to="admissions.admittedstudent",
                    ),
                ),
            ],
            options={
                "ordering": ["-assigned_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "academic_year", "term_number"],
                        name="hostel_host_status_4ecd57_idx",
                    ),
                    models.Index(
                        fields=["student", "status"],
                        name="hostel_host_student_c7fc3e_idx",
                    ),
                    models.Index(
                        fields=["bed", "status"], name="hostel_host_bed_id_f7f574_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "active")),
                        fields=("student",),
                        name="hostel_one_active_allocation_per_student",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "active")),
                        fields=("bed",),
                        name="hostel_one_active_allocation_per_bed",
                    ),
                ],
            },
        ),
    ]
