# Generated by Django 5.2.7 on 2026-08-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_seed_hostel_manager_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='continuing_max_sort_order',
            field=models.PositiveSmallIntegerField(default=2, help_text='Suggested floors for continuing students: floors with sort_order <= this value (lower levels).'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='fresher_min_sort_order',
            field=models.PositiveSmallIntegerField(default=3, help_text='Suggested floors for freshers (Y1): floors with sort_order >= this value (upper levels). Set equal to continuing_max+1 typically.'),
        ),
    ]
