# Generated by Django 5.2.7 on 2025-11-03 07:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Programs', '0001_initial'),
        ('accounts', '0008_remove_campus_is_active_remove_campus_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ALevelSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'A-Level Subject',
                'verbose_name_plural': 'A-Level Subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OLevelSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'O-Level Subject',
                'verbose_name_plural': 'O-Level Subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='NDU Admission Portal', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('nationality', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('next_of_kin_name', models.CharField(blank=True, help_text='Full name of next of kin', max_length=200)),
                ('next_of_kin_contact', models.CharField(blank=True, help_text='Phone number of next of kin', max_length=20)),
                ('next_of_kin_relationship', models.CharField(blank=True, choices=[('parent', 'Parent'), ('guardian', 'Guardian'), ('sibling', 'Sibling'), ('spouse', 'Spouse'), ('other', 'Other')], help_text='Relationship to next of kin', max_length=20)),
                ('olevel_year', models.PositiveIntegerField()),
                ('olevel_index_number', models.CharField(max_length=50)),
                ('olevel_school', models.CharField(max_length=200)),
                ('alevel_year', models.PositiveIntegerField()),
                ('alevel_index_number', models.CharField(max_length=50)),
                ('alevel_school', models.CharField(max_length=200)),
                ('additional_qualification_institution', models.CharField(blank=True, help_text='Institution Name', max_length=200)),
                ('additional_qualification_type', models.CharField(blank=True, choices=[('certificate', 'Certificate'), ('diploma', 'Diploma'), ('degree', 'Degree')], help_text='Qualification Type', max_length=20)),
                ('additional_qualification_year', models.PositiveIntegerField(blank=True, help_text='Award Year', null=True)),
                ('passport_photo', models.ImageField(blank=True, help_text='Passport Photo (JPG/PNG, ≤ 2MB)', null=True, upload_to='passport_photos/')),
                ('payment_proof', models.FileField(blank=True, help_text='Payment Proof (PDF)', null=True, upload_to='payment_proofs/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='draft', max_length=20)),
                ('application_fee_paid', models.BooleanField(default=False)),
                ('application_fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.campus')),
                ('programs', models.ManyToManyField(blank=True, help_text='Programs the applicant applied for', related_name='application_programs', to='Programs.program')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='application_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admissions.application')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('application_start_date', models.DateTimeField()),
                ('application_end_date', models.DateTimeField()),
                ('admission_start_date', models.DateTimeField()),
                ('admission_end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_batches', to=settings.AUTH_USER_MODEL)),
                ('programs', models.ManyToManyField(related_name='batches', to='Programs.program')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Batch will be assigned during admission', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='admissions.batch'),
        ),
        migrations.CreateModel(
            name='AdmittedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(help_text='Student ID number', max_length=50, unique=True)),
                ('admission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('admission_letter_sent', models.BooleanField(default=False)),
                ('admission_letter_sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_registered', models.BooleanField(default=False)),
                ('registration_date', models.DateTimeField(blank=True, null=True)),
                ('admission_notes', models.TextField(blank=True, help_text='Notes about the admission')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admitted_students', to=settings.AUTH_USER_MODEL)),
                ('admitted_campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admitted_students', to='accounts.campus')),
                ('admitted_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admitted_students', to='Programs.program')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='admissions.application')),
                ('admitted_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admitted_students', to='admissions.batch')),
            ],
            options={
                'verbose_name': 'Admitted Student',
                'verbose_name_plural': 'Admitted Students',
                'ordering': ['-admission_date'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('dean_name', models.CharField(blank=True, max_length=200)),
                ('dean_email', models.EmailField(blank=True, max_length=254)),
                ('dean_phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campuses', models.ManyToManyField(blank=True, related_name='faculties', to='accounts.campus')),
            ],
            options={
                'verbose_name_plural': 'Faculties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PortalNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('link_url', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ALevelResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('O', 'O'), ('F', 'F')], max_length=1)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.alevelsubject')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alevel_results', to='admissions.application')),
            ],
            options={
                'verbose_name': 'A-Level Result',
                'verbose_name_plural': 'A-Level Results',
                'ordering': ['subject__name'],
                'unique_together': {('application', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='OLevelResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('D1', 'D1'), ('D2', 'D2'), ('C3', 'C3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6'), ('P7', 'P7'), ('P8', 'P8'), ('F9', 'F9')], max_length=2)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olevel_results', to='admissions.application')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.olevelsubject')),
            ],
            options={
                'verbose_name': 'O-Level Result',
                'verbose_name_plural': 'O-Level Results',
                'ordering': ['subject__name'],
                'unique_together': {('application', 'subject')},
            },
        ),
    ]
