# Generated by Django 5.2.7 on 2026-05-07 10:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Programs', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ALevelSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'A-Level Subject',
                'verbose_name_plural': 'A-Level Subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OLevelSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'O-Level Subject',
                'verbose_name_plural': 'O-Level Subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdmittedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('study_mode', models.CharField(max_length=30)),
                ('reg_no', models.CharField(max_length=100, unique=True)),
                ('admission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('admission_letter_sent', models.BooleanField(default=False)),
                ('admission_letter_sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_admitted', models.BooleanField(default=False)),
                ('is_registered', models.BooleanField(default=False)),
                ('registration_date', models.DateTimeField(blank=True, null=True)),
                ('admission_notes', models.TextField(blank=True, help_text='Notes about the admission')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admitted_campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admitted_students', to='accounts.campus')),
                ('admitted_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Programs.program')),
            ],
            options={
                'verbose_name': 'Admitted Student',
                'verbose_name_plural': 'Admitted Students',
                'ordering': ['-admission_date'],
                'permissions': [('verify_physical_documents', 'Can verify physical admission documents')],
            },
        ),
        migrations.CreateModel(
            name='AdmissionChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('program', 'Programme Change'), ('campus', 'Campus Transfer'), ('study_mode', 'Study Mode Change'), ('dead_semester', 'Dead Semester'), ('dead_year', 'Dead Year')], max_length=20)),
                ('current_study_mode', models.CharField(blank=True, max_length=30)),
                ('new_study_mode', models.CharField(blank=True, max_length=30)),
                ('requested_year', models.PositiveSmallIntegerField(blank=True, help_text='Year of study being declared dead (e.g. 1, 2, 3)', null=True)),
                ('requested_semester', models.PositiveSmallIntegerField(blank=True, help_text='Semester number being declared dead (e.g. 1 or 2); leave blank for dead year', null=True)),
                ('reason', models.TextField(help_text="Student's reason for requesting the change")),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Admin notes on approval or rejection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.campus')),
                ('current_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='Programs.program')),
                ('new_campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests', to='accounts.campus')),
                ('new_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests', to='Programs.program')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_change_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_change_requests', to=settings.AUTH_USER_MODEL)),
                ('admitted_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='admissions.admittedstudent')),
            ],
            options={
                'verbose_name': 'Admission Change Request',
                'verbose_name_plural': 'Admission Change Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(blank=True, max_length=40, null=True)),
                ('nin', models.CharField(blank=True, max_length=20, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True)),
                ('disabled', models.CharField(blank=True, max_length=5, null=True)),
                ('next_of_kin_name', models.CharField(max_length=200)),
                ('next_of_kin_contact', models.CharField(max_length=25)),
                ('next_of_kin_relationship', models.CharField(max_length=20)),
                ('olevel_year', models.PositiveIntegerField(blank=True, null=True)),
                ('olevel_index_number', models.CharField(blank=True, max_length=50, null=True)),
                ('olevel_school', models.CharField(blank=True, max_length=200, null=True)),
                ('has_olevel', models.BooleanField(default=False)),
                ('has_alevel', models.BooleanField(default=False)),
                ('alevel_year', models.PositiveIntegerField(blank=True, null=True)),
                ('alevel_index_number', models.CharField(blank=True, max_length=50, null=True)),
                ('alevel_school', models.CharField(blank=True, max_length=200, null=True)),
                ('alevel_combination', models.CharField(blank=True, max_length=10, null=True)),
                ('source', models.CharField(choices=[('portal', 'Applicant Portal'), ('direct_entry', 'Direct Entry'), ('legacy_import', 'Legacy Import')], default='portal', max_length=30)),
                ('legacy_application_number', models.CharField(blank=True, max_length=100, null=True)),
                ('is_direct_entry', models.BooleanField(default=False)),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='passport_photos/')),
                ('payment_proof', models.FileField(blank=True, help_text='Payment Proof (PDF)', null=True, upload_to='payment_proofs/')),
                ('status', models.CharField(default='draft', max_length=20)),
                ('application_reference', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('application_fee_paid', models.BooleanField(default=False)),
                ('application_fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('admission_letter_docx', models.FileField(blank=True, null=True, upload_to='admission_template/')),
                ('admission_letter_pdf', models.FileField(blank=True, null=True, upload_to='admission_template/')),
                ('offer_letter_status', models.CharField(default='pending', max_length=20)),
                ('offer_letter_progress', models.IntegerField(default=0)),
                ('offer_letter_verification_token', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('offer_letter_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.academiclevel')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.campus')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_applications', to=settings.AUTH_USER_MODEL)),
                ('offer_letter_generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_offer_letters', to=settings.AUTH_USER_MODEL)),
                ('programs', models.ManyToManyField(related_name='application_programs', to='Programs.program')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='admittedstudent',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='admissions.application'),
        ),
        migrations.CreateModel(
            name='AdditionalQualifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_qualification_institution', models.CharField(blank=True, help_text='Institution Name', max_length=200)),
                ('additional_qualification_type', models.CharField(blank=True, max_length=30)),
                ('additional_qualification_year', models.PositiveIntegerField(blank=True, help_text='Award Year', null=True)),
                ('class_of_award', models.CharField(blank=True, max_length=200, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additionals', to='admissions.application')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=40)),
                ('academic_year', models.CharField(blank=True, max_length=25)),
                ('application_start_date', models.DateField()),
                ('application_end_date', models.DateField()),
                ('admission_start_date', models.DateField()),
                ('admission_end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_batches', to=settings.AUTH_USER_MODEL)),
                ('programs', models.ManyToManyField(related_name='batches', to='Programs.program')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='admissions.batch'),
        ),
        migrations.AddField(
            model_name='admittedstudent',
            name='admitted_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admitted_students', to='admissions.batch'),
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campuses', models.ManyToManyField(blank=True, related_name='faculties', to='accounts.campus')),
            ],
            options={
                'verbose_name_plural': 'Faculties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OLevelResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=10)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olevel_results', to='admissions.application')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.olevelsubject')),
            ],
            options={
                'verbose_name': 'O-Level Result',
                'verbose_name_plural': 'O-Level Results',
                'ordering': ['subject__name'],
            },
        ),
        migrations.CreateModel(
            name='PortalNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ALevelResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=10)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.alevelsubject')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alevel_results', to='admissions.application')),
            ],
            options={
                'verbose_name': 'A-Level Result',
                'verbose_name_plural': 'A-Level Results',
                'ordering': ['subject__name'],
                'indexes': [models.Index(fields=['application'], name='admissions__applica_e590ac_idx')],
                'unique_together': {('application', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('document_type', models.CharField(max_length=30)),
                ('file_url', models.URLField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(upload_to='application_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admissions.application')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['application'], name='admissions__applica_ddce04_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status', 'created_at'], name='admissions__status_bb96e5_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applicant'], name='admissions__applica_7e8475_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['batch'], name='admissions__batch_i_d2acf1_idx'),
        ),
        migrations.AddIndex(
            model_name='admittedstudent',
            index=models.Index(fields=['application', 'created_at'], name='admissions__applica_b459f8_idx'),
        ),
        migrations.AddIndex(
            model_name='admittedstudent',
            index=models.Index(fields=['is_registered'], name='admissions__is_regi_b441b2_idx'),
        ),
        migrations.AddIndex(
            model_name='admittedstudent',
            index=models.Index(fields=['admitted_batch', 'is_admitted'], name='admissions__admitte_031e75_idx'),
        ),
        migrations.AddIndex(
            model_name='admittedstudent',
            index=models.Index(fields=['is_admitted'], name='admissions__is_admi_b28160_idx'),
        ),
        migrations.AddIndex(
            model_name='olevelresult',
            index=models.Index(fields=['application'], name='admissions__applica_e909ba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='olevelresult',
            unique_together={('application', 'subject')},
        ),
        migrations.AddIndex(
            model_name='portalnotification',
            index=models.Index(fields=['recipient'], name='admissions__recipie_93b244_idx'),
        ),
    ]
