# Generated by Django 5.2.7 on 2026-05-07 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
    ]
