# Generated by Django 5.2.7 on 2026-05-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='next_of_kin_contact',
            field=models.CharField(max_length=35),
        ),
    ]
