# Generated by Django 5.2.7 on 2025-11-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_remove_academiclevel_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='alevel_combination',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
