# Generated by Django 5.2.7 on 2026-05-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_alter_application_next_of_kin_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='next_of_kin_contact',
            field=models.CharField(max_length=25),
        ),
    ]
