# Generated by Django 5.2.7 on 2026-05-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_auto_20260507_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='school_pay_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
