# Generated by Django 5.2.7 on 2026-05-04 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_application_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='title',
        ),
    ]
