# Generated by Django 5.2.7 on 2026-05-07 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_application_school_pay_reference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at'], 'permissions': [('approve_candidate', 'Can approve candidate')]},
        ),
    ]
