# Generated by Django 5.2.7 on 2025-11-03 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_application_alevel_combination'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='academic_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admissions.academiclevel'),
        ),
    ]
