# Generated by Django 5.2.7 on 2026-05-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_remove_application_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
