# Generated by Django 5.2.7 on 2025-11-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_application_academic_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdocument',
            name='file_url',
            field=models.URLField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='name',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
