# Generated by Django 5.2.7 on 2026-05-07 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_alter_application_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at']},
        ),
    ]
