# Generated by Django 5.2.7 on 2026-05-07 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_alter_application_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admittedstudent',
            options={'ordering': ['-admission_date'], 'permissions': [('verify_physical_documents', 'Can verify physical admission documents'), ('revoke_admission', 'Can revoke admitted students')], 'verbose_name': 'Admitted Student', 'verbose_name_plural': 'Admitted Students'},
        ),
        migrations.AddField(
            model_name='admittedstudent',
            name='is_revoked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admittedstudent',
            name='revocation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='admittedstudent',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admittedstudent',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_admissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='admissionchangerequest',
            name='admitted_student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='admissions.admittedstudent'),
            preserve_default=False,
        ),
    ]
