# Generated by Django 5.2.7 on 2025-11-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_applicationdocument_file_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdocument',
            name='file_url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
