# Generated by Django 5.2.5 on 2026-05-08 10:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0006_alter_admittedstudent_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IDCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_number", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generated", "Generated"),
                            ("printed", "Printed"),
                            ("active", "Active"),
                            ("revoked", "Revoked"),
                            ("reissued", "Reissued"),
                        ],
                        default="generated",
                        max_length=20,
                    ),
                ),
                ("issue_date", models.DateField(default=django.utils.timezone.now)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("barcode_value", models.CharField(max_length=150, unique=True)),
                (
                    "verification_token",
                    models.CharField(db_index=True, max_length=80, unique=True),
                ),
                ("template_version", models.CharField(default="v1", max_length=20)),
                ("print_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admitted_student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="id_cards",
                        to="admissions.admittedstudent",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_id_cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="IDCardPrintLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("generate", "Generate"),
                            ("print", "Print"),
                            ("reprint", "Reprint"),
                            ("reissue", "Reissue"),
                            ("revoke", "Revoke"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="admissions.idcard",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="id_card_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-performed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="idcard",
            index=models.Index(
                fields=["admitted_student", "is_active"],
                name="admissions__admitte_4ef2df_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="idcard",
            index=models.Index(fields=["status"], name="admissions__status_e9eb79_idx"),
        ),
        migrations.AddConstraint(
            model_name="idcard",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("admitted_student",),
                name="unique_active_id_card_per_student",
            ),
        ),
        migrations.AddIndex(
            model_name="idcardprintlog",
            index=models.Index(
                fields=["id_card", "action"], name="admissions__id_card_4538a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="idcardprintlog",
            index=models.Index(
                fields=["performed_at"], name="admissions__perform_7c8d18_idx"
            ),
        ),
    ]
