# Generated by Django 5.2.7 on 2026-05-08 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0006_alter_admittedstudent_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admittedstudent',
            name='is_revoked',
        ),
        migrations.RemoveField(
            model_name='admittedstudent',
            name='revocation_reason',
        ),
        migrations.RemoveField(
            model_name='admittedstudent',
            name='revoked_at',
        ),
        migrations.RemoveField(
            model_name='admittedstudent',
            name='revoked_by',
        ),
        migrations.AddField(
            model_name='application',
            name='is_revoked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='revocation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='application',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_admissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
