# Generated by Django 5.2.7 on 2025-11-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0006_alter_applicationdocument_file_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdocument',
            name='document_type',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
