# Generated by Django 5.2.5 on 2026-05-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0007_remove_admittedstudent_is_revoked_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="address",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
