# Generated by Django 5.2.7 on 2025-11-06 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0007_applicationdocument_document_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='dean_email',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='dean_name',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='dean_phone',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='description',
        ),
    ]
