# Generated by Django 5.2.7 on 2025-11-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0008_remove_faculty_dean_email_remove_faculty_dean_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admittedstudent',
            name='reg_no',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admittedstudent',
            name='student_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
