# Generated by Django 5.2.5 on 2026-05-10 18:53

from django.db import migrations, models


def backfill_schoolpay_code(apps, schema_editor):
    AdmittedStudent = apps.get_model("admissions", "AdmittedStudent")
    for row in AdmittedStudent.objects.filter(schoolpay_code="").exclude(reg_no=""):
        row.schoolpay_code = str(row.reg_no).strip()
        row.save(update_fields=["schoolpay_code"])


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0008_alter_application_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="admittedstudent",
            name="schoolpay_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Official SchoolPay / PRN shown to the student. Left blank at admission to default to reg_no on save; finance may set a different value if the gateway uses another number.",
                max_length=100,
            ),
        ),
        migrations.RunPython(backfill_schoolpay_code, migrations.RunPython.noop),
    ]
