# Generated by Django 5.2.7 on 2025-11-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0009_admittedstudent_reg_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='study_mode',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
