# Generated by Django 5.2.7 on 2026-05-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0009_admittedstudent_admitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='admittedstudent',
            name='schoolpay_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
