# Generated by Django 5.2.7 on 2025-11-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0010_application_study_mode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSettings',
        ),
        migrations.AddField(
            model_name='application',
            name='admission_letter_docx',
            field=models.FileField(blank=True, null=True, upload_to='admission_template/'),
        ),
        migrations.AddField(
            model_name='application',
            name='admission_letter_pdf',
            field=models.FileField(blank=True, null=True, upload_to='admission_template/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='additional_qualification_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='next_of_kin_relationship',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(default='draft', max_length=20),
        ),
    ]
