# Generated by Django 5.2.7 on 2026-05-11 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0009_admittedstudent_admitted_by"),
        ("admissions", "0010_admittedstudent_student_user"),
    ]

    operations = []
