# Generated by Django 5.2.7 on 2026-05-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0011_alter_admittedstudent_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='admittedstudent',
            name='is_registered_with_schoolpay',
            field=models.BooleanField(default=False),
        ),
    ]
