# Generated by Django 5.2.7 on 2025-11-10 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0011_delete_sitesettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admittedstudent',
            name='admitted_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admitted_students', to='admissions.batch'),
        ),
    ]
