# Generated by Django 5.2.7 on 2026-05-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0012_admittedstudent_is_registered_with_schoolpay"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admittedstudent",
            name="schoolpay_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Official SchoolPay / PRN shown to the student. Left blank at admission to default to reg_no on save; finance may set a different value if the gateway uses another number.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="admittedstudent",
            name="student_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
