# Generated by Django 5.2.7 on 2025-11-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0012_alter_admittedstudent_admitted_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='admittedstudent',
            name='is_admitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alevelresult',
            name='grade',
            field=models.CharField(max_length=1),
        ),
    ]
