# Generated by Django 5.2.7 on 2025-11-14 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0003_bulkuploadprograms'),
        ('admissions', '0013_admittedstudent_is_admitted_alter_alevelresult_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='academic_year',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admittedstudent',
            name='admitted_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Programs.program'),
        ),
    ]
