# Generated by Django 5.2.7 on 2025-11-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0014_batch_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='academic_year',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
