# Generated by Django 5.2.7 on 2026-05-11 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0011_merge_20260511_1015'),
        ('admissions', '0015_emailtemplate'),
    ]

    operations = [
    ]
