# Generated by Django 5.2.7 on 2025-11-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0015_alter_batch_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='class_of_award',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
