# Generated by Django 5.2.5 on 2026-05-13 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0015_emailtemplate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="admissionchangerequest",
            options={
                "default_permissions": ("add", "change", "delete", "view"),
                "ordering": ["-created_at"],
                "permissions": [
                    (
                        "manage_admission_change_requests",
                        "Can approve or reject admission change requests (programme, campus, etc.)",
                    )
                ],
                "verbose_name": "Admission Change Request",
                "verbose_name_plural": "Admission Change Requests",
            },
        ),
        migrations.AlterModelOptions(
            name="application",
            options={
                "default_permissions": ("add", "change", "delete", "view"),
                "ordering": ["-created_at"],
                "permissions": [
                    (
                        "approve_application",
                        "Can approve applications (mark accepted for admission processing)",
                    ),
                    ("reject_application", "Can reject applications"),
                    (
                        "admit_applicant",
                        "Can admit applicants (create or finalize admission records)",
                    ),
                ],
            },
        ),
    ]
