# Generated by Django 5.2.7 on 2025-11-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0016_application_class_of_award'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='study_mode',
            field=models.CharField(max_length=10),
        ),
    ]
