# Generated by Django 5.2.7 on 2026-05-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0016_merge_0011_merge_20260511_1015_0015_emailtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admittedstudent',
            name='schoolpay_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
