# Generated by Django 5.2.5 on 2026-05-13 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0017_seed_admission_workflow_permissions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="admittedstudent",
            options={
                "ordering": ["-admission_date"],
                "permissions": [
                    (
                        "verify_physical_documents",
                        "Can verify physical admission documents",
                    ),
                    ("revoke_admission", "Can revoke admitted students"),
                    ("restore_revoked_admission", "Can restore revoked admissions"),
                ],
                "verbose_name": "Admitted Student",
                "verbose_name_plural": "Admitted Students",
            },
        ),
        migrations.AlterModelOptions(
            name="application",
            options={
                "default_permissions": ("add", "change", "delete", "view"),
                "ordering": ["-created_at"],
                "permissions": [
                    (
                        "approve_application",
                        "Can approve applications (mark accepted for admission processing)",
                    ),
                    ("reject_application", "Can reject applications"),
                    (
                        "admit_applicant",
                        "Can admit applicants (create or finalize admission records)",
                    ),
                    (
                        "edit_application_registration",
                        "Can edit applicant registration data and programme choices (admin)",
                    ),
                ],
            },
        ),
    ]
