# Generated by Django 5.2.7 on 2026-05-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0017_alter_admittedstudent_schoolpay_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admittedstudent',
            name='student_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
