# Generated by Django 5.2.7 on 2025-11-18 18:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0017_alter_application_study_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='academiclevel',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
