# Generated by Django 5.2.7 on 2025-11-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0018_academiclevel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='admission_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='batch',
            name='admission_start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='batch',
            name='application_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='batch',
            name='application_start_date',
            field=models.DateField(),
        ),
    ]
