# Generated by Django 5.2.7 on 2026-05-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0018_alter_admittedstudent_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='admittedstudent',
            name='admission_fee_paid',
            field=models.BooleanField(default=False),
        ),
    ]
