# Generated by Django 5.2.5 on 2026-05-13 11:14

import django.db.models.deletion
import django.utils.timezone
from django.apps import apps as django_apps
from django.conf import settings
from django.contrib.auth.management import create_permissions
from django.contrib.contenttypes.management import create_contenttypes
from django.db import migrations, models


def grant_student_id_officer_id_card_perms(apps, schema_editor):
    db = schema_editor.connection.alias
    app_config = django_apps.get_app_config("admissions")
    create_contenttypes(app_config, verbosity=0, interactive=False, using=db)
    create_permissions(app_config, verbosity=0, interactive=False, using=db)

    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    group = Group.objects.using(db).filter(name="Student ID Officer").first()
    if not group:
        return
    for codename in ("manage_id_cards", "view_studentidcard"):
        perm = (
            Permission.objects.using(db)
            .filter(
                content_type__app_label="admissions",
                content_type__model="studentidcard",
                codename=codename,
            )
            .first()
        )
        if perm:
            group.permissions.add(perm)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0018_extended_permissions_v2"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentIdCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card_number",
                    models.CharField(db_index=True, max_length=48, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generated", "Generated"),
                            ("printed", "Printed"),
                            ("active", "Active"),
                            ("revoked", "Revoked"),
                            ("reissued", "Reissued"),
                        ],
                        default="generated",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="False when revoked or superseded by a reissue.",
                    ),
                ),
                ("issue_date", models.DateField(default=django.utils.timezone.now)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("print_count", models.PositiveIntegerField(default=0)),
                ("revoke_reason", models.TextField(blank=True, default="")),
                ("reissue_reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admitted_student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="id_cards",
                        to="admissions.admittedstudent",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_id_cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "replaced_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supersedes",
                        to="admissions.studentidcard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student ID card",
                "verbose_name_plural": "Student ID cards",
                "ordering": ["-created_at"],
                "permissions": [
                    ("manage_id_cards", "Issue, revoke, and reissue student ID cards")
                ],
                "indexes": [
                    models.Index(
                        fields=["admitted_student", "is_active"],
                        name="admissions__admitte_9e4381_idx",
                    ),
                    models.Index(
                        fields=["status"], name="admissions__status_bdf2a7_idx"
                    ),
                ],
            },
        ),
        migrations.RunPython(grant_student_id_officer_id_card_perms, noop_reverse),
    ]
