# Generated by Django 5.2.7 on 2026-05-13 21:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0004_merge_20260512_0115'),
        ('accounts', '0024_seed_admissions_custom_roles'),
        ('admissions', '0019_admittedstudent_admission_fee_paid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='admittedstudent',
            index=models.Index(fields=['student_id'], name='admissions__student_ea9b04_idx'),
        ),
    ]
