# Generated by Django 5.2.7 on 2025-11-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0019_alter_batch_admission_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portalnotification',
            name='link_url',
        ),
        migrations.AlterField(
            model_name='olevelresult',
            name='grade',
            field=models.CharField(max_length=2),
        ),
    ]
