# Generated by Django 5.2.5 on 2026-05-13 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Programs", "0004_program_curriculum_inheritance"),
        ("accounts", "0026_student_id_cards_and_settings"),
        ("admissions", "0019_student_id_cards_and_settings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="admittedstudent",
            name="physical_documents_notes",
            field=models.TextField(
                blank=True,
                help_text="Staff notes when documents were verified at the desk",
            ),
        ),
        migrations.AddField(
            model_name="admittedstudent",
            name="physical_documents_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="admittedstudent",
            name="physical_documents_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="admittedstudent",
            name="physical_documents_verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="physical_document_verifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="admittedstudent",
            index=models.Index(
                fields=["physical_documents_verified"],
                name="admissions__physica_a984e2_idx",
            ),
        ),
    ]
