# Generated by Django 5.2.7 on 2026-05-13 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0019_admittedstudent_admission_fee_paid'),
        ('admissions', '0020_admittedstudent_admissions__student_ea9b04_idx'),
    ]

    operations = [
    ]
