# Generated by Django 5.2.7 on 2025-11-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0020_remove_portalnotification_link_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='application_documents/'),
        ),
    ]
