# Generated by Django 5.2.7 on 2026-05-14 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Programs", "0004_program_curriculum_inheritance"),
        ("admissions", "0021_idcardpdftemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="admittedstudent",
            name="intended_program_batch",
            field=models.ForeignKey(
                blank=True,
                help_text="The academic cohort this student should be placed in. Set at time of admission.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="intended_admissions",
                to="Programs.programbatch",
            ),
        ),
    ]
