# Generated by Django 5.2.7 on 2025-11-21 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0007_alter_bulkuploadprograms_error_log'),
        ('admissions', '0021_alter_applicationdocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='academic_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admissions.academiclevel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='admissions.batch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='next_of_kin_contact',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='next_of_kin_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='application',
            name='next_of_kin_relationship',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='passport_photo',
            field=models.ImageField(default=1, upload_to='passport_photos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='programs',
            field=models.ManyToManyField(related_name='application_programs', to='Programs.program'),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='file',
            field=models.FileField(default=1, upload_to='application_documents/'),
            preserve_default=False,
        ),
    ]
