# Generated by Django 5.2.7 on 2026-05-14 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0004_merge_20260512_0115'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationProgramChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_choices', to='admissions.application')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Programs.program')),
            ],
            options={
                'ordering': ['choice_order'],
                'unique_together': {('application', 'choice_order')},
            },
        ),
    ]
