# Generated by Django 5.2.7 on 2025-11-25 09:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0022_alter_application_academic_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='admission_letter_docx',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='admission_letter_docx'),
        ),
        migrations.AlterField(
            model_name='application',
            name='admission_letter_pdf',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='admission_letter_pdf'),
        ),
        migrations.AlterField(
            model_name='application',
            name='passport_photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='passport_photo'),
        ),
        migrations.AlterField(
            model_name='application',
            name='payment_proof',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='payment_proof'),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='document'),
        ),
    ]
