# Generated by Django 5.2.7 on 2026-05-14 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0022_applicationprogramchoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='programs',
        ),
    ]
