# Generated by Django 5.2.5 on 2026-05-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0022_admittedstudent_intended_program_batch"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="offer_end_date",
            field=models.DateField(
                blank=True,
                help_text="Date after which admission offers for this batch expire and the batch is no longer shown as active.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="offer_start_date",
            field=models.DateField(
                blank=True,
                help_text="Date from which admission offers become active for this batch.",
                null=True,
            ),
        ),
    ]
