# Generated by Django 5.2.7 on 2026-05-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0004_merge_20260512_0115'),
        ('admissions', '0023_remove_application_programs'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='programs',
            field=models.ManyToManyField(blank=True, related_name='application_programs', to='Programs.program'),
        ),
    ]
