# Generated by Django 5.2.7 on 2025-11-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0023_alter_application_admission_letter_docx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='admission_letter_docx',
            field=models.FileField(blank=True, null=True, upload_to='admission_template/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='admission_letter_pdf',
            field=models.FileField(blank=True, null=True, upload_to='admission_template/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='passport_photo',
            field=models.ImageField(upload_to='passport_photos/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='payment_proof',
            field=models.FileField(blank=True, help_text='Payment Proof (PDF)', null=True, upload_to='payment_proofs/'),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='file',
            field=models.FileField(upload_to='application_documents/'),
        ),
    ]
