# Generated by Django 5.2.5 on 2026-05-14 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0021_merge_20260514_0211"),
        ("admissions", "0023_batch_offer_dates"),
    ]

    operations = []
