# Generated by Django 5.2.7 on 2025-11-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0024_alter_application_admission_letter_docx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='offer_letter_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='offer_letter_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
