# Generated by Django 5.2.7 on 2026-05-15 01:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Programs", "0006_programbatch_offer_dates"),
        ("admissions", "0024_merge_0021_merge_20260514_0211_0023_batch_offer_dates"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationProgramChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preference",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="1 = first choice; higher numbers = lower priority.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(50),
                        ],
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_choices",
                        to="admissions.application",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_choices",
                        to="Programs.program",
                    ),
                ),
            ],
            options={
                "ordering": ["preference", "pk"],
                "indexes": [
                    models.Index(
                        fields=["application", "preference"],
                        name="admissions__applica_2931f9_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("application", "program"),
                        name="admissions_appprogchoice_application_program_uniq",
                    ),
                    models.UniqueConstraint(
                        fields=("application", "preference"),
                        name="admissions_appprogchoice_application_preference_uniq",
                    ),
                ],
            },
        ),
    ]
