# Generated by Django 5.2.7 on 2026-05-14 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0023_batch_offer_dates'),
        ('admissions', '0025_remove_application_programs'),
    ]

    operations = [
    ]
