# Generated by Django 5.2.7 on 2025-11-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0025_application_offer_letter_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
