# Generated by Django 5.2.7 on 2026-02-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0026_alter_batch_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_reference',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
