# Generated by Django 5.2.7 on 2026-06-05 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # Former parent 0024_merge_0021_merge_... was removed during main merge;
        # 0023_batch_offer_dates is the surviving leaf from that branch.
        ('admissions', '0023_batch_offer_dates'),
        ('admissions', '0027_academicyear'),
    ]

    operations = [
    ]
