# Generated by Django 5.2.7 on 2026-05-15 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0024_merge_0021_merge_20260514_0211_0023_batch_offer_dates'),
        ('admissions', '0027_application_program_choice_confirmation'),
    ]

    operations = [
    ]
