# Generated by Django 5.2.7 on 2026-02-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0027_application_application_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='nin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
