# Generated by Django 5.2.7 on 2026-02-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0028_application_nin_application_passport_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='address',
            field=models.TextField(blank=True, max_length=40, null=True),
        ),
    ]
