# Generated by Django 5.2.7 on 2026-06-05 21:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0011_alter_venue_options_alter_venue_name'),
        ('admissions', '0028_merge_20260606_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationProgramChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_order', models.PositiveSmallIntegerField(default=1, help_text='1 = first choice; higher numbers = lower priority.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_choices', to='admissions.application')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_choices', to='Programs.program')),
            ],
            options={
                'ordering': ['choice_order', 'pk'],
                'indexes': [models.Index(fields=['application', 'choice_order'], name='admissions__applica_0b8eb4_idx')],
                'constraints': [models.UniqueConstraint(fields=('application', 'program'), name='admissions_appprogchoice_application_program_uniq'), models.UniqueConstraint(fields=('application', 'choice_order'), name='admissions_appprogchoice_application_choice_order_uniq')],
            },
        ),
    ]
