# Generated by Django 5.2.7 on 2026-06-05 21:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0029_applicationprogramchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationprogramchoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
