# Generated by Django 5.2.7 on 2026-02-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0029_alter_application_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='disabled',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
