# Generated by Django 5.2.7 on 2026-03-18 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0030_application_disabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='study_mode',
        ),
    ]
