# Generated by Django 5.2.5 on 2026-05-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0030_application_program_choices_confirmed_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="program_choices_confirmed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When programme choices were confirmed in the portal (applicant or staff).",
                null=True,
            ),
        ),
    ]
