# Generated by Django 5.2.7 on 2026-03-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0031_remove_application_study_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='admittedstudent',
            name='study_mode',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
