# Generated by Django 5.2.7 on 2026-05-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0031_alter_application_program_choices_confirmed_at_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='pending_reason',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
