# Generated by Django 5.2.7 on 2026-03-20 18:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0007_alter_bulkuploadprograms_error_log'),
        ('accounts', '0013_alter_user_is_applicant'),
        ('admissions', '0032_admittedstudent_study_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='admittedstudent',
            index=models.Index(fields=['application', 'created_at'], name='admissions__applica_b459f8_idx'),
        ),
        migrations.AddIndex(
            model_name='admittedstudent',
            index=models.Index(fields=['is_registered'], name='admissions__is_regi_b441b2_idx'),
        ),
        migrations.AddIndex(
            model_name='admittedstudent',
            index=models.Index(fields=['admitted_batch', 'is_admitted'], name='admissions__admitte_031e75_idx'),
        ),
        migrations.AddIndex(
            model_name='admittedstudent',
            index=models.Index(fields=['is_admitted'], name='admissions__is_admi_b28160_idx'),
        ),
        migrations.AddIndex(
            model_name='alevelresult',
            index=models.Index(fields=['application'], name='admissions__applica_e590ac_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status', 'created_at'], name='admissions__status_bb96e5_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applicant'], name='admissions__applica_7e8475_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['batch'], name='admissions__batch_i_d2acf1_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationdocument',
            index=models.Index(fields=['application'], name='admissions__applica_ddce04_idx'),
        ),
        migrations.AddIndex(
            model_name='olevelresult',
            index=models.Index(fields=['application'], name='admissions__applica_e909ba_idx'),
        ),
        migrations.AddIndex(
            model_name='portalnotification',
            index=models.Index(fields=['recipient'], name='admissions__recipie_93b244_idx'),
        ),
    ]
