# Generated by Django 5.2.7 on 2026-05-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0032_application_pending_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalqualifications',
            name='additional_qualification_year',
            field=models.CharField(blank=True, help_text='Award Year', max_length=15, null=True),
        ),
    ]
