# Generated by Django 5.2.7 on 2026-05-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0033_alter_additionalqualifications_additional_qualification_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalqualifications',
            name='additional_qualification_year',
            field=models.CharField(blank=True, help_text='Award Year', max_length=100, null=True),
        ),
    ]
