# Generated by Django 5.2.7 on 2026-03-24 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0033_admittedstudent_admissions__applica_b459f8_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admittedstudent',
            name='admitted_batch',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='admitted_students', to='admissions.batch'),
            preserve_default=False,
        ),
    ]
