# Generated by Django 5.2.7 on 2026-03-28 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0034_alter_admittedstudent_admitted_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='additional_qualification_institution',
        ),
        migrations.RemoveField(
            model_name='application',
            name='additional_qualification_type',
        ),
        migrations.RemoveField(
            model_name='application',
            name='additional_qualification_year',
        ),
        migrations.RemoveField(
            model_name='application',
            name='class_of_award',
        ),
        migrations.CreateModel(
            name='AdditionalQualifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_qualification_institution', models.CharField(blank=True, help_text='Institution Name', max_length=200)),
                ('additional_qualification_type', models.CharField(blank=True, max_length=20)),
                ('additional_qualification_year', models.PositiveIntegerField(blank=True, help_text='Award Year', null=True)),
                ('class_of_award', models.CharField(blank=True, max_length=200, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additionals', to='admissions.application')),
            ],
        ),
    ]
