# Generated by Django 5.2.7 on 2026-06-05 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0019_admittedstudent_admission_fee_paid'),
        ('admissions', '0020_admittedstudent_admissions__student_ea9b04_idx'),
        ('admissions', '0023_batch_offer_dates'),
        ('admissions', '0025_remove_application_programs'),
        ('admissions', '0027_academicyear'),
        ('admissions', '0027_application_program_choice_confirmation'),
        ('admissions', '0034_alter_additionalqualifications_additional_qualification_year'),
    ]

    operations = [
    ]
