# Generated by Django 5.2.7 on 2026-03-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0035_remove_application_additional_qualification_institution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalqualifications',
            name='additional_qualification_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='admittedstudent',
            name='study_mode',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='alevelresult',
            name='grade',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_reference',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='batch',
            name='academic_year',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='batch',
            name='code',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='olevelresult',
            name='grade',
            field=models.CharField(max_length=10),
        ),
    ]
