# Generated by Django 5.2.7 on 2026-06-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0035_merge_20260606_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='program_choices_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='When programme choices were confirmed in the portal (applicant or staff).', null=True),
        ),
    ]
