# Generated by Django 5.2.7 on 2026-03-31 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0036_alter_additionalqualifications_additional_qualification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_reference',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
