# Generated by Django 5.2.7 on 2026-04-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0038_application_admitted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='alevel_combination',
            field=models.CharField(max_length=10),
        ),
    ]
