# Generated by Django 5.2.5 on 2026-04-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0039_alter_application_alevel_combination"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="is_direct_entry",
            field=models.BooleanField(default=False),
        ),
    ]
