# Generated by Django 5.2.7 on 2026-04-20 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0038_application_entered_by_and_more'),
        ('admissions', '0040_application_is_direct_entry'),
    ]

    operations = [
    ]
