# Generated by Django 5.2.7 on 2026-04-20 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0041_merge_0038_migrations'),
        ('admissions', '0041_merge_20260420_1747'),
    ]

    operations = [
    ]
