# Generated by Django 5.2.7 on 2026-04-23 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0043_repair_application_missing_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='has_alevel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='has_olevel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alevelresult',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alevel_results', to='admissions.application'),
        ),
        migrations.AlterField(
            model_name='alevelresult',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='alevelresult',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admissions.alevelsubject'),
        ),
        migrations.AlterField(
            model_name='olevelresult',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='olevel_results', to='admissions.application'),
        ),
        migrations.AlterField(
            model_name='olevelresult',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='olevelresult',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admissions.olevelsubject'),
        ),
    ]
