# Generated by Django 5.2.7 on 2026-04-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0044_application_has_alevel_application_has_olevel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='alevel_combination',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='alevel_index_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='alevel_school',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='alevel_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
