# Generated by Django 5.2.7 on 2026-04-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0045_alter_application_alevel_combination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='address',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='olevel_index_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='olevel_school',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='olevel_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
