# Generated by Django 5.2.7 on 2026-04-24 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0046_alter_application_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='alevel_combination',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
