# Generated by Django 5.2.7 on 2026-07-15 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0030_applicationprogramchoice_created_at'),
        ('admissions', '0047_application_applicant_category'),
    ]

    operations = [
    ]
