# Generated by Django 5.2.5 on 2026-07-22 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Programs", "0019_course_material"),
        ("admissions", "0047_application_applicant_category"),
        ("payments", "0007_feeplanrule_billing_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="admissionchangerequest",
            options={
                "default_permissions": ("add", "change", "delete", "view"),
                "ordering": ["-created_at"],
                "permissions": [
                    (
                        "manage_admission_change_requests",
                        "Can approve or reject admission change requests (programme, campus, etc.)",
                    ),
                    (
                        "approve_exemption_requests",
                        "Can approve or reject course exemption change requests",
                    ),
                ],
                "verbose_name": "Admission Change Request",
                "verbose_name_plural": "Admission Change Requests",
            },
        ),
        migrations.AddField(
            model_name="admissionchangerequest",
            name="form_fee_charge",
            field=models.ForeignKey(
                blank=True,
                help_text="Ad-hoc charge that unlocks the exemption application form.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exemption_form_fee_for_requests",
                to="payments.studenttuitionpayment",
            ),
        ),
        migrations.AddField(
            model_name="admissionchangerequest",
            name="form_fee_paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="admissionchangerequest",
            name="change_type",
            field=models.CharField(
                choices=[
                    ("program", "Programme Change"),
                    ("campus", "Campus Transfer"),
                    ("study_mode", "Study Mode Change"),
                    ("dead_semester", "Dead Semester"),
                    ("dead_year", "Dead Year"),
                    ("exemption", "Course Exemption"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ExemptionRequestLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_code",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "course_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "year_of_study",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "term_number",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "change_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exemption_lines",
                        to="admissions.admissionchangerequest",
                    ),
                ),
                (
                    "curriculum_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exemption_request_lines",
                        to="Programs.programcurriculumline",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exemption Request Line",
                "verbose_name_plural": "Exemption Request Lines",
                "ordering": ["year_of_study", "term_number", "course_code", "id"],
            },
        ),
    ]
