# Generated by Django 5.2.5 on 2026-07-22 17:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Programs", "0019_course_material"),
        ("admissions", "0049_student_portal_account_action"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="admittedstudent",
            name="admission_fee_paid",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name="admittedstudent",
            index=models.Index(
                fields=["is_admitted", "admission_fee_paid", "-created_at"],
                name="admitted_bonafide_list_idx",
            ),
        ),
    ]
