# Generated by Django 5.2.7 on 2026-07-24 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Programs", "0019_course_material"),
        ("accounts", "0042_manage_scholarships"),
        ("admissions", "0050_admitted_bonafide_list_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="admittedstudent",
            options={
                "ordering": ["-admission_date"],
                "permissions": [
                    (
                        "verify_physical_documents",
                        "Can verify physical admission documents",
                    ),
                    (
                        "clear_accounts_registration",
                        "Can clear students for registration after payment",
                    ),
                    ("revoke_admission", "Can revoke admitted students"),
                    ("restore_revoked_admission", "Can restore revoked admissions"),
                ],
                "verbose_name": "Admitted Student",
                "verbose_name_plural": "Admitted Students",
            },
        ),
        migrations.AddField(
            model_name="admittedstudent",
            name="accounts_registration_clearance_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="admittedstudent",
            name="accounts_registration_cleared",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Accounts confirmed payment and cleared student for registration / document verification.",
            ),
        ),
        migrations.AddField(
            model_name="admittedstudent",
            name="accounts_registration_cleared_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="admittedstudent",
            name="accounts_registration_cleared_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accounts_registration_clearances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="admittedstudent",
            index=models.Index(
                fields=["accounts_registration_cleared"],
                name="admissions__account_d40c3d_idx",
            ),
        ),
    ]
