# Generated by Django 5.2.7 on 2026-04-29 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0050_application_legacy_application_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admittedstudent",
            name="approved_at",
        ),
        migrations.RemoveField(
            model_name="admittedstudent",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="admittedstudent",
            name="is_approved",
        ),
    ]
