# Generated by Django 5.2.5 on 2026-07-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0051_accounts_registration_clearance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admittedstudent",
            name="accounts_registration_cleared",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Accounts confirmed payment and cleared this student. Required before the student portal registration card is available (new and continuing students).",
            ),
        ),
    ]
