# Generated by Django 5.2.7 on 2026-07-29 10:33
# Made idempotent: production already had these columns added outside django_migrations.

from django.conf import settings
from django.db import migrations, models


def _pg_column_exists(cursor, table: str, column: str) -> bool:
    cursor.execute(
        """
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = %s AND column_name = %s
        """,
        [table, column],
    )
    return cursor.fetchone() is not None


def _pg_index_exists(cursor, index_name: str) -> bool:
    cursor.execute(
        """
        SELECT 1
        FROM pg_indexes
        WHERE indexname = %s
        """,
        [index_name],
    )
    return cursor.fetchone() is not None


def apply_tuition_pct_cache(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        # Non-Postgres: fall back to normal AddField via schema_editor when missing.
        AdmittedStudent = apps.get_model("admissions", "AdmittedStudent")
        table = AdmittedStudent._meta.db_table
        with schema_editor.connection.cursor() as cursor:
            # Best-effort: try ALTER and ignore duplicate errors.
            for sql in (
                f'ALTER TABLE "{table}" ADD COLUMN "registration_tuition_pct_at" timestamp with time zone NULL',
                f'ALTER TABLE "{table}" ADD COLUMN "registration_tuition_pct_met" boolean DEFAULT false NOT NULL',
            ):
                try:
                    cursor.execute(sql)
                except Exception:
                    pass
        return

    table = "admissions_admittedstudent"
    with schema_editor.connection.cursor() as cursor:
        if not _pg_column_exists(cursor, table, "registration_tuition_pct_at"):
            cursor.execute(
                f'ALTER TABLE "{table}" '
                'ADD COLUMN "registration_tuition_pct_at" timestamp with time zone NULL'
            )
        if not _pg_column_exists(cursor, table, "registration_tuition_pct_met"):
            cursor.execute(
                f'ALTER TABLE "{table}" '
                'ADD COLUMN "registration_tuition_pct_met" boolean DEFAULT false NOT NULL'
            )
        cursor.execute(
            f'CREATE INDEX IF NOT EXISTS "admissions_a_registr_tuition_pct_at_idx" '
            f'ON "{table}" ("registration_tuition_pct_at")'
        )
        cursor.execute(
            f'CREATE INDEX IF NOT EXISTS "admissions_a_registr_tuition_pct_met_idx" '
            f'ON "{table}" ("registration_tuition_pct_met")'
        )
        if not _pg_index_exists(cursor, "admitted_bonafide_tuition_idx"):
            cursor.execute(
                f'CREATE INDEX "admitted_bonafide_tuition_idx" ON "{table}" '
                '("is_admitted", "admission_fee_paid", "registration_tuition_pct_met", '
                '"created_at" DESC)'
            )


def noop_reverse(apps, schema_editor):
    # Do not drop columns — they may have been present before this migration.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("Programs", "0020_alter_lectureattendancerecord_marked_via"),
        ("accounts", "0043_alter_user_allow_multi_campus_per_day_and_more"),
        ("admissions", "0052_alter_admittedstudent_accounts_registration_cleared"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="admittedstudent",
                    name="registration_tuition_pct_at",
                    field=models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When registration_tuition_pct_met was last computed.",
                        null=True,
                    ),
                ),
                migrations.AddField(
                    model_name="admittedstudent",
                    name="registration_tuition_pct_met",
                    field=models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text=(
                            "True when current-term tuition payment meets RegistrationSettings "
                            "minimum %. Used for fast Bonafide/Accounts list filters."
                        ),
                    ),
                ),
                migrations.AddIndex(
                    model_name="admittedstudent",
                    index=models.Index(
                        fields=[
                            "is_admitted",
                            "admission_fee_paid",
                            "registration_tuition_pct_met",
                            "-created_at",
                        ],
                        name="admitted_bonafide_tuition_idx",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(apply_tuition_pct_cache, noop_reverse),
            ],
        ),
    ]
