# Generated by Django 5.2.7 on 2026-07-29 10:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0020_alter_lectureattendancerecord_marked_via'),
        ('accounts', '0043_alter_user_allow_multi_campus_per_day_and_more'),
        ('admissions', '0052_alter_admittedstudent_accounts_registration_cleared'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='admittedstudent',
            name='registration_tuition_pct_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When registration_tuition_pct_met was last computed.', null=True),
        ),
        migrations.AddField(
            model_name='admittedstudent',
            name='registration_tuition_pct_met',
            field=models.BooleanField(db_index=True, default=False, help_text='True when current-term tuition payment meets RegistrationSettings minimum %. Used for fast Bonafide/Accounts list filters.'),
        ),
        migrations.AddIndex(
            model_name='admittedstudent',
            index=models.Index(fields=['is_admitted', 'admission_fee_paid', 'registration_tuition_pct_met', '-created_at'], name='admitted_bonafide_tuition_idx'),
        ),
    ]
