# Generated by Django 5.2.5 on 2026-05-02 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _application_column_names(connection, table_name):
    with connection.cursor() as cursor:
        desc = connection.introspection.get_table_description(cursor, table_name)
    return {col.name for col in desc}


def _ensure_legacy_and_source_columns(apps, schema_editor):
    """DB may already have these from 0052; AddField would duplicate columns."""
    Application = apps.get_model("admissions", "Application")
    table = Application._meta.db_table
    conn = schema_editor.connection
    names = _application_column_names(conn, table)
    qn = conn.ops.quote_name
    with conn.cursor() as cursor:
        if "legacy_application_number" not in names:
            cursor.execute(
                f"ALTER TABLE {qn(table)} ADD COLUMN {qn('legacy_application_number')} VARCHAR(100) NULL"
            )
        if "source" not in names:
            cursor.execute(
                f"ALTER TABLE {qn(table)} ADD COLUMN {qn('source')} VARCHAR(30) NOT NULL DEFAULT 'portal'"
            )


class Migration(migrations.Migration):

    dependencies = [
        ("Programs", "0012_coursecatalogunit_program_calendar_type_and_more"),
        ("accounts", "0022_alter_erpaccesspolicy_options_alter_profile_phone_and_more"),
        ("admissions", "0052_application_add_source_columns"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="admitted_by",
        ),
        migrations.RemoveField(
            model_name="application",
            name="has_alevel",
        ),
        migrations.RemoveField(
            model_name="application",
            name="has_olevel",
        ),
        migrations.RemoveField(
            model_name="application",
            name="school_pay_reference",
        ),
        migrations.AddField(
            model_name="admittedstudent",
            name="student_user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_admission",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    _ensure_legacy_and_source_columns,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="application",
                    name="legacy_application_number",
                    field=models.CharField(blank=True, max_length=100, null=True),
                ),
                migrations.AddField(
                    model_name="application",
                    name="source",
                    field=models.CharField(
                        choices=[
                            ("portal", "Applicant Portal"),
                            ("direct_entry", "Direct Entry"),
                            ("legacy_import", "Legacy Import"),
                        ],
                        default="portal",
                        max_length=30,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="application",
            name="offer_letter_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="offer_letter_generated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_offer_letters",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="offer_letter_verification_token",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="alevelresult",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alevel_results",
                to="admissions.application",
            ),
        ),
        migrations.AlterField(
            model_name="alevelresult",
            name="grade",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="alevelresult",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="admissions.alevelsubject",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="address",
            field=models.TextField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="alevel_combination",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="application",
            name="alevel_index_number",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="application",
            name="alevel_school",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="application",
            name="alevel_year",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="application",
            name="olevel_index_number",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="application",
            name="olevel_school",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="application",
            name="olevel_year",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="application",
            name="passport_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="passport_photos/"
            ),
        ),
        migrations.AlterField(
            model_name="applicationdocument",
            name="name",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="olevelresult",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="olevel_results",
                to="admissions.application",
            ),
        ),
        migrations.AlterField(
            model_name="olevelresult",
            name="grade",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="olevelresult",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="admissions.olevelsubject",
            ),
        ),
        migrations.CreateModel(
            name="AdmissionChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("program", "Programme Change"),
                            ("campus", "Campus Transfer"),
                            ("study_mode", "Study Mode Change"),
                            ("dead_semester", "Dead Semester"),
                            ("dead_year", "Dead Year"),
                        ],
                        max_length=20,
                    ),
                ),
                ("current_study_mode", models.CharField(blank=True, max_length=30)),
                ("new_study_mode", models.CharField(blank=True, max_length=30)),
                (
                    "requested_year",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Year of study being declared dead (e.g. 1, 2, 3)",
                        null=True,
                    ),
                ),
                (
                    "requested_semester",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Semester number being declared dead (e.g. 1 or 2); leave blank for dead year",
                        null=True,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Student's reason for requesting the change"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_notes",
                    models.TextField(
                        blank=True, help_text="Admin notes on approval or rejection"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admitted_student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_requests",
                        to="admissions.admittedstudent",
                    ),
                ),
                (
                    "current_campus",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounts.campus",
                    ),
                ),
                (
                    "current_program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="Programs.program",
                    ),
                ),
                (
                    "new_campus",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfer_requests",
                        to="accounts.campus",
                    ),
                ),
                (
                    "new_program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfer_requests",
                        to="Programs.program",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_change_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_change_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Admission Change Request",
                "verbose_name_plural": "Admission Change Requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
