# Generated by Django 5.2.7 on 2026-07-31 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0053_admittedstudent_registration_tuition_pct_cache"),
    ]

    operations = [
        migrations.AddField(
            model_name="exemptionrequestline",
            name="score_obtained",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Score/grade the student obtained in this course at the previous institution (e.g. 65, B+, 3.5 GPA).",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ExemptionSupportingDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("transcript", "Academic transcript"),
                            ("certificate", "Certificate"),
                            ("other", "Other supporting document"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="exemption_documents/")),
                (
                    "original_filename",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "change_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supporting_documents",
                        to="admissions.admissionchangerequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exemption Supporting Document",
                "verbose_name_plural": "Exemption Supporting Documents",
                "ordering": ["uploaded_at"],
            },
        ),
    ]
