# Generated by Django 5.2.5 on 2026-08-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0056_studentportalaccountaction_reset_password_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="admissionchangerequest",
            name="exemption_academic_years",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Academic year(s) the credit was earned in (e.g. '2019/2020').",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="admissionchangerequest",
            name="exemption_attained_at",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Institution where the exempted credit was earned (e.g. 'Uganda Management Institute').",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="admissionchangerequest",
            name="exemption_is_alumnus",
            field=models.BooleanField(
                default=False,
                help_text="Did the student complete their undergraduate studies at this university? Drives the discounted per-paper exemption fee rate.",
            ),
        ),
    ]
