# Generated by Django 5.2.5 on 2026-08-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0057_exemption_pricing_basis"),
    ]

    operations = [
        migrations.AddField(
            model_name="exemptionrequestline",
            name="decision",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="exemptionrequestline",
            name="decision_note",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional note when a paper is rejected (shown to reviewers).",
                max_length=255,
            ),
        ),
    ]
