# Generated by Django 5.2.5 on 2026-08-14 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0061_temporary_access_pass_bursar_approval"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=40)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Academic department",
                "verbose_name_plural": "Academic departments",
                "ordering": ["faculty__name", "sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="academicdepartment",
            name="faculty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="admissions.faculty",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="academicdepartment",
            unique_together={("faculty", "code"), ("faculty", "name")},
        ),
    ]
