# Generated by Django 5.2.7 on 2026-08-14 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0062_accounts_registration_cleared_email'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='temporaryaccesspass',
            new_name='admissions__student_cd7e16_idx',
            old_name='admissions__student_b8e2a1_idx',
        ),
        migrations.RenameIndex(
            model_name='temporaryaccesspass',
            new_name='admissions__status_6c1e71_idx',
            old_name='admissions__status_9c4d2f_idx',
        ),
    ]
