# Generated by Django 5.2.5 on 2026-09-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0072_exemption_promotion_from_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="admissionchangerequest",
            name="exemption_verification_token",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Token embedded in the HOD exemption print QR for public verification.",
                null=True,
                unique=True,
            ),
        ),
    ]
