# Generated by Django 5.2.5 on 2026-10-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0076_fix_role_permissions_timing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admissionchangerequest",
            name="change_type",
            field=models.CharField(
                choices=[
                    ("program", "Programme Change"),
                    ("campus", "Campus Transfer"),
                    ("study_mode", "Study Mode Change"),
                    ("dead_semester", "Dead Semester"),
                    ("dead_year", "Dead Year"),
                    ("exemption", "Course Exemption"),
                    ("transfer_credit", "Transfer Credit"),
                ],
                max_length=20,
            ),
        ),
    ]
