# Generated by Django 5.2.5 on 2026-10-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0078_admittedstudent_university_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="admittedstudent",
            name="university_email_deactivated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the Zimbra mailbox was deactivated (e.g. after admission revocation). Null = still active.",
                null=True,
            ),
        ),
    ]
