# Generated by Django 5.2.5 on 2026-05-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="active_id_card_template",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Template key currently used for ID card rendering.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="id_card_templates",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of configurable ID card templates.",
            ),
        ),
    ]
