# Generated by Django 5.2.7 on 2025-10-30 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_username_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='campuses',
            new_name='campus',
        ),
    ]
