# Generated by Django 5.2.7 on 2025-10-30 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_campuses_user_campus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='campus',
            new_name='campuses',
        ),
    ]
