# Generated by Django 5.2.7 on 2025-11-03 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_username_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campus',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='phone',
        ),
    ]
