# Generated by Django 5.2.7 on 2026-03-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_profile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_applicant',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
