# Generated by Django 5.2.7 on 2026-03-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_is_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='campus',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
