# Generated by Django 5.2.5 on 2026-04-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_alter_campus_address_alter_campus_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campus",
            name="address",
            field=models.TextField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="campus",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=100),
        ),
    ]
