# Generated by Django 5.2.7 on 2026-04-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_alter_campus_address_alter_campus_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="date_joined",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="passport_photos/"
            ),
        ),
    ]
