# Generated by Django 5.2.7 on 2026-04-20 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_campus_address_alter_campus_email'),
        ('accounts', '0015_alter_profile_date_joined_alter_profile_phone_and_more'),
    ]

    operations = [
    ]
