# Generated by Django 5.2.5 on 2026-04-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_systemsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemsettings",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
