# Generated by Django 5.2.7 on 2026-04-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_alter_systemsettings_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_lecturer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_student",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="staff_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
