# Generated by Django 5.2.5 on 2026-05-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_seed_erp_access_groups"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="erpaccesspolicy",
            options={
                "default_permissions": (),
                "permissions": [
                    ("access_admissions", "Access Admissions module"),
                    (
                        "access_academics",
                        "Access Academics (programmes, curriculum, enrollment)",
                    ),
                    ("access_finance", "Access Finance and payments"),
                    ("access_reports", "Access Reports and analytics"),
                    ("access_user_management", "Access user administration"),
                    ("access_audit", "Access audit logs"),
                    ("access_system_settings", "Access academic and admission setup"),
                    ("access_lecturer_portal", "Access lecturer workspace"),
                    ("manage_direct_applications", "Manage direct-entry applications"),
                    (
                        "approve_admissions",
                        "Approve or reject applications and admissions",
                    ),
                    ("manage_batches", "Manage admission intakes and batches"),
                    ("assign_roles", "Assign Django groups to staff users"),
                    (
                        "manage_payment_reconciliation",
                        "Manage payment reconciliation tools",
                    ),
                ],
                "verbose_name": "ERP access policy",
                "verbose_name_plural": "ERP access policies",
            },
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_lecturer",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_student",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="staff_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, null=True, unique=True
            ),
        ),
    ]
