# Generated by Django 5.2.5 on 2026-05-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0025_extended_permissions_v2"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="active_id_card_template",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Template key matching id_card_templates[].key",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="id_card_templates",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of {key, name, front_title, back_text, ...} objects for ID card preview.",
            ),
        ),
    ]
