# Generated by Django 5.2.5 on 2026-05-15 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0026_student_id_cards_and_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemsettings",
            name="id_card_templates",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of {key, name, front_title, back_text, institution, issuer_title, issuer_signatory, return_to, tel, email} for ID card preview.",
            ),
        ),
    ]
