# Generated by Django 5.2.7 on 2026-06-05 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_user_campus_attendance_fields'),
        ('accounts', '0030_access_graduation_and_initial'),
    ]

    operations = [
    ]
