# Generated by Django 5.2.7 on 2026-07-29 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_manage_scholarships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='allow_multi_campus_per_day',
            field=models.BooleanField(default=False, help_text='If false, timetable blocks same lecturer on two campuses in one day.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='primary_campus',
            field=models.ForeignKey(blank=True, help_text='Main teaching campus (used for timetable campus rules).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_staff', to='accounts.campus'),
        ),
    ]
