# Generated by Django 5.2.5 on 2026-09-18 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0051_user_staff_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicCalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("start_date", models.DateField()),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank for a single-day event.",
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("registration", "Registration / Reporting"),
                            ("orientation", "Orientation"),
                            ("exam", "Examinations / Tests"),
                            ("deadline", "Deadline"),
                            ("holiday", "Public Holiday / Break"),
                            ("event", "University Event"),
                            ("meeting", "Internal Meeting"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("students", "Students"),
                            ("staff", "Staff only"),
                            ("all", "Everyone"),
                        ],
                        default="students",
                        max_length=20,
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. 2026/2027 — informational, not used for filtering.",
                        max_length=20,
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Academic calendar event",
                "ordering": ["start_date", "id"],
            },
        ),
    ]
