# Generated by Django 5.2.7 on 2026-09-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0052_academiccalendarevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="restrict_lecturer_roster_to_registered",
            field=models.BooleanField(
                default=False,
                help_text="When on, lecturers only see registered (registration_date set) or active-scholarship students in My Students, attendance, marks entry, and course roster counts -- everyone else is hidden until they register or are awarded a scholarship.",
            ),
        ),
    ]
