# Generated by Django 5.2.7 on 2025-11-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('register', 'register')], max_length=20),
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
