# Generated by Django 5.2.5 on 2026-05-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_alter_auditlog_action_delete_useractivity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("register", "register"),
                    ("phys_verify", "Physical documents verified"),
                    ("phys_clear", "Physical documents verification cleared"),
                ],
                max_length=32,
            ),
        ),
    ]
