# Generated by Django 5.2.5 on 2026-05-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0003_physical_document_verification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("register", "register"),
                    ("phys_verify", "Physical documents verified"),
                    ("phys_clear", "Physical documents verification cleared"),
                    ("id_card_generate", "ID card generated"),
                    ("id_card_revoke", "ID card revoked"),
                    ("id_card_reissue", "ID card reissued"),
                    ("passport_photo_update", "Passport / ID photo updated at desk"),
                    ("passport_photo_delete", "Passport / ID photo removed at desk"),
                ],
                max_length=32,
            ),
        ),
    ]
