# Generated by Django 5.2.7 on 2026-06-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_passport_photo_delete_audit_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=32),
        ),
    ]
