# Generated by Django 5.2.7 on 2026-06-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_audit_program_choice_admin_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=32),
        ),
    ]
