# Generated by Django 5.2.7 on 2026-07-15 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_alter_auditlog_action'),
        ('audit', '0006_alter_auditlog_action'),
    ]

    operations = [
    ]
