# Generated by Django 5.2.5 on 2026-07-07 11:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_staff", models.BooleanField(default=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=5)),
                ("current_address", models.TextField(max_length=100)),
                ("religious_affiliation", models.CharField(max_length=20)),
                ("marital_status", models.CharField(max_length=20)),
                ("dob", models.CharField(max_length=20)),
                ("brief_description", models.TextField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("APPLIED", "Application Received"),
                            ("SCREENING", "Under Screening"),
                            ("SHORTLISTED", "Shortlisted"),
                            ("INTERVIEWING", "Interview Scheduled"),
                            ("SELECTED", "Selected for Offer"),
                            ("HIRED", "hired for job"),
                            ("ACCEPTED", "Offer Accepted"),
                            ("REJECTED", "Rejected"),
                            ("WITHDRAWN", "Application Withdrawn"),
                            ("RESERVED", "application reserved"),
                        ],
                        default="APPLIED",
                        max_length=20,
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("application_date", models.DateTimeField(auto_now_add=True)),
                ("has_declared", models.BooleanField(default=False)),
                ("skills", models.TextField(max_length=500)),
                (
                    "reference",
                    models.CharField(
                        blank=True, editable=False, max_length=20, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Application",
                "verbose_name_plural": "Job Applications",
                "ordering": ["-application_date"],
            },
        ),
        migrations.CreateModel(
            name="JobOpening",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("FULL_TIME", "Full Time"),
                            ("PART_TIME", "Part Time"),
                            ("CONTRACT", "Contract"),
                            ("TEMPORARY", "Temporary"),
                            ("INTERNSHIP", "Internship"),
                        ],
                        default="FULL_TIME",
                        max_length=20,
                    ),
                ),
                ("description", models.FileField(upload_to="job_descriptions/")),
                (
                    "number_of_positions",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("application_deadline", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("OPEN", "Open for Applications"),
                            ("CLOSED", "Closed"),
                            ("CANCELLED", "Cancelled"),
                            ("FILLED", "Position Filled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("published_date", models.DateField()),
            ],
            options={
                "verbose_name": "Job Opening",
                "verbose_name_plural": "Job Openings",
                "ordering": ["-published_date"],
            },
        ),
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("link", models.URLField()),
                ("description", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="References",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("phone", models.PositiveIntegerField()),
                ("email", models.EmailField(max_length=30)),
                ("job_position", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interview_type", models.CharField(max_length=20)),
                ("interview_date", models.DateTimeField()),
                ("duration_minutes", models.IntegerField(default=60)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("meeting_link", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("PASSED", "passed"),
                            ("FAILED", "failed"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("RESCHEDULED", "Rescheduled"),
                            ("NO_SHOW", "Candidate No Show"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                ("feedback", models.TextField(blank=True, max_length=500)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="hiring.jobapplication",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interview",
                "verbose_name_plural": "Interviews",
                "ordering": ["-interview_date"],
            },
        ),
        migrations.CreateModel(
            name="Employment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_employer", models.CharField(max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("current_position", models.CharField(max_length=200)),
                (
                    "years_of_experience",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("duties", models.TextField(max_length=300)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hiring.jobapplication",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EducationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institution", models.CharField(max_length=20)),
                ("award", models.CharField(max_length=20)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hiring.jobapplication",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Certificates_and_Training",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("certificate_name", models.CharField(max_length=30)),
                ("institution", models.CharField(max_length=30)),
                ("date_obtained", models.DateField()),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hiring.jobapplication",
                    ),
                ),
            ],
        ),
    ]
