# Generated by Django 5.2.5 on 2026-07-07 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hiring", "0001_initial"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobopening",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_openings",
                to="staff.department",
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="job_opening",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="hiring.jobopening",
            ),
        ),
        migrations.AddField(
            model_name="projects",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hiring.jobapplication"
            ),
        ),
        migrations.AddField(
            model_name="references",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hiring.jobapplication"
            ),
        ),
    ]
