# Generated by Django 5.2.5 on 2026-08-13 12:50

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MoodleApiAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.CharField(max_length=120)),
                ("key_prefix", models.CharField(blank=True, default="", max_length=16)),
                ("http_status", models.PositiveSmallIntegerField(default=200)),
                ("detail", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Moodle API access log",
                "verbose_name_plural": "Moodle API access logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MoodleIntegrationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                (
                    "api_key_prefix",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "api_key_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("moodle_base_url", models.URLField(blank=True, default="")),
                (
                    "cleared_min_percent",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("100.0"),
                        help_text="Minimum tuition % paid for CLEARED status.",
                        max_digits=5,
                    ),
                ),
                (
                    "partial_min_percent",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("50.0"),
                        help_text="Minimum tuition % paid for PARTIAL status (below CLEARED).",
                        max_digits=5,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Moodle integration config",
                "verbose_name_plural": "Moodle integration config",
            },
        ),
    ]
