# Generated by Django 5.2.5 on 2026-10-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0003_zimbra_integration_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="zimbraintegrationconfig",
            name="preauth_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Domain preauth key for Zimbra SSO launch (zmprov gdpak <domain> on the mail server). Never returned by the API. Lets students open webmail from the student portal without re-entering their Zimbra password.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="zimbraintegrationconfig",
            name="webmail_base_url",
            field=models.URLField(
                blank=True,
                default="https://ndejjemail.ndu.ac.ug",
                help_text="Student-facing webmail URL (no trailing slash) used for SSO launch.",
            ),
        ),
    ]
