# Generated by Django 5.2.7 on 2026-05-06 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Programs', '0001_initial'),
        ('accounts', '0001_initial'),
        ('admissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courseunit',
            name='lecturers',
            field=models.ManyToManyField(blank=True, help_text='Staff assigned to teach this course unit', related_name='course_units', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='program',
            name='academic_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.academiclevel'),
        ),
        migrations.AddField(
            model_name='program',
            name='campuses',
            field=models.ManyToManyField(blank=True, related_name='programs', to='accounts.campus'),
        ),
        migrations.AddField(
            model_name='program',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='admissions.faculty'),
        ),
        migrations.AddField(
            model_name='programbatch',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_batches', to='Programs.program'),
        ),
        migrations.AddField(
            model_name='courseunit',
            name='program_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_units', to='Programs.programbatch'),
        ),
        migrations.AddField(
            model_name='programcurriculumline',
            name='catalog_course',
            field=models.ForeignKey(help_text='Catalogue entry being mapped into this programme slot.', on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_lines', to='Programs.coursecatalogunit'),
        ),
        migrations.AddField(
            model_name='programcurriculumline',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_lines', to='Programs.program'),
        ),
        migrations.AddField(
            model_name='courseunit',
            name='curriculum_line',
            field=models.ForeignKey(blank=True, help_text='Optional link to the curriculum blueprint this operational course was created from. Set this to make the course traceable to the programme curriculum.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offered_course_units', to='Programs.programcurriculumline'),
        ),
        migrations.AddField(
            model_name='programcurriculumversion',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_versions', to='Programs.program'),
        ),
        migrations.AddField(
            model_name='programcurriculumline',
            name='curriculum_version',
            field=models.ForeignKey(help_text='Curriculum version this line belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='Programs.programcurriculumversion'),
        ),
        migrations.AddField(
            model_name='programbatch',
            name='curriculum_version',
            field=models.ForeignKey(blank=True, help_text='Curriculum version used by this cohort/batch. If blank, fallback logic resolves the programme default.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='program_batches', to='Programs.programcurriculumversion'),
        ),
        migrations.AddField(
            model_name='programspecialization',
            name='program',
            field=models.ForeignKey(help_text='The programme this track belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='Programs.program'),
        ),
        migrations.AddField(
            model_name='semester',
            name='program_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='Programs.programbatch'),
        ),
        migrations.AddField(
            model_name='courseunit',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_units', to='Programs.semester'),
        ),
        migrations.AddField(
            model_name='studentcourseunitenrollment',
            name='course_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='Programs.courseunit'),
        ),
        migrations.AddField(
            model_name='studentcourseunitenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_unit_enrollments', to='admissions.admittedstudent'),
        ),
        migrations.AddField(
            model_name='studentcurriculumoverride',
            name='curriculum_line',
            field=models.ForeignKey(help_text='The blueprint line being overridden for this student.', on_delete=django.db.models.deletion.CASCADE, related_name='student_overrides', to='Programs.programcurriculumline'),
        ),
        migrations.AddField(
            model_name='studentcurriculumoverride',
            name='decided_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who created this override.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curriculum_override_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentcurriculumoverride',
            name='substituted_by',
            field=models.ForeignKey(blank=True, help_text='The curriculum line that satisfies this one (for substituted type).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitutes_for', to='Programs.programcurriculumline'),
        ),
        migrations.AddField(
            model_name='studentprogrammeenrollment',
            name='curriculum_version',
            field=models.ForeignKey(blank=True, help_text='Pinned curriculum version for this student. Once set, expected/registration courses resolve from this version.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_enrollments', to='Programs.programcurriculumversion'),
        ),
        migrations.AddField(
            model_name='studentprogrammeenrollment',
            name='enrolled_by',
            field=models.ForeignKey(blank=True, help_text='Admin who confirmed the commitment fee and activated enrollment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentprogrammeenrollment',
            name='program',
            field=models.ForeignKey(help_text='Must match program_batch.program.', on_delete=django.db.models.deletion.PROTECT, related_name='student_enrollments', to='Programs.program'),
        ),
        migrations.AddField(
            model_name='studentprogrammeenrollment',
            name='program_batch',
            field=models.ForeignKey(help_text='The academic cohort the student is placed in.', on_delete=django.db.models.deletion.PROTECT, related_name='student_enrollments', to='Programs.programbatch'),
        ),
        migrations.AddField(
            model_name='studentprogrammeenrollment',
            name='student',
            field=models.OneToOneField(help_text='Each admitted student has at most one academic enrollment record.', on_delete=django.db.models.deletion.CASCADE, related_name='programme_enrollment', to='admissions.admittedstudent'),
        ),
        migrations.AddField(
            model_name='studentcurriculumoverride',
            name='enrollment',
            field=models.ForeignKey(help_text='The academic enrollment this override belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_overrides', to='Programs.studentprogrammeenrollment'),
        ),
        migrations.AddField(
            model_name='studentsemesterprogression',
            name='program_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progressions', to='Programs.programbatch'),
        ),
        migrations.AddField(
            model_name='studentsemesterprogression',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progressions', to='Programs.semester'),
        ),
        migrations.AddField(
            model_name='studentsemesterprogression',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_progressions', to='admissions.admittedstudent'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['code'], name='Programs_pr_code_5998d9_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['name'], name='Programs_pr_name_8ea6f8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='programcurriculumversion',
            unique_together={('program', 'name')},
        ),
        migrations.AddConstraint(
            model_name='programcurriculumline',
            constraint=models.UniqueConstraint(fields=('curriculum_version', 'catalog_course', 'year_of_study', 'term_number'), name='unique_curriculum_slot'),
        ),
        migrations.AlterUniqueTogether(
            name='programbatch',
            unique_together={('program', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='programspecialization',
            unique_together={('program', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('program_batch', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='courseunit',
            unique_together={('code', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='studentcourseunitenrollment',
            unique_together={('student', 'course_unit')},
        ),
        migrations.AddConstraint(
            model_name='studentcurriculumoverride',
            constraint=models.UniqueConstraint(fields=('enrollment', 'curriculum_line'), name='unique_student_curriculum_override'),
        ),
        migrations.AlterUniqueTogether(
            name='studentsemesterprogression',
            unique_together={('student', 'semester')},
        ),
    ]
