# Generated by Django 5.2.7 on 2026-05-02 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Programs', '0001_initial'),
        ('accounts', '0019_user_is_lecturer_user_is_student_and_more'),
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='academic_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.academiclevel'),
        ),
        migrations.AddField(
            model_name='program',
            name='campuses',
            field=models.ManyToManyField(blank=True, related_name='programs', to='accounts.campus'),
        ),
        migrations.AddField(
            model_name='program',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='admissions.faculty'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['code'], name='Programs_pr_code_5998d9_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['name'], name='Programs_pr_name_8ea6f8_idx'),
        ),
    ]
