# Generated by Django 5.2.7 on 2025-11-03 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Programs', '0001_initial'),
        ('accounts', '0008_remove_campus_is_active_remove_campus_phone'),
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='academic_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.academiclevel'),
        ),
        migrations.AddField(
            model_name='program',
            name='campuses',
            field=models.ManyToManyField(blank=True, related_name='programs', to='accounts.campus'),
        ),
        migrations.AddField(
            model_name='program',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='admissions.faculty'),
        ),
    ]
