# Generated by Django 5.2.7 on 2026-05-11 10:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='calendar_type',
            field=models.CharField(choices=[('semester', 'Semester'), ('trimester', 'Trimester')], default='semester', help_text='Academic calendar structure: semester (2 terms/year) or trimester (3 terms/year).', max_length=20),
        ),
        migrations.AddField(
            model_name='program',
            name='has_specialization',
            field=models.BooleanField(default=False, help_text='Set to True if this programme branches into specialization tracks.'),
        ),
        migrations.AddField(
            model_name='program',
            name='minimum_graduation_load',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum total credit units a student must accumulate to graduate from this programme.', max_digits=6),
        )
    ]
