# Generated by Django 5.2.5 on 2026-05-11 09:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Programs", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="calendar_type",
            field=models.CharField(
                choices=[("semester", "Semester"), ("trimester", "Trimester")],
                default="semester",
                help_text="Academic calendar structure: semester (2 terms/year) or trimester (3 terms/year).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="has_specialization",
            field=models.BooleanField(
                default=False,
                help_text="Set to True if this programme branches into specialization tracks.",
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="minimum_graduation_load",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Minimum total credit units a student must accumulate to graduate from this programme.",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="specialization_entry_term",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Term within specialization_entry_year when the choice is required (e.g. 1 for the first term of Year 3).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="specialization_entry_year",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Year of study when students must choose a specialization (e.g. 3 for Year 3). Only relevant when has_specialization is True.",
                null=True,
            ),
        ),
    ]
