# Generated by Django 5.2.7 on 2026-05-07 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='calendar_type',
        ),
        migrations.RemoveField(
            model_name='program',
            name='has_specialization',
        ),
        migrations.RemoveField(
            model_name='program',
            name='minimum_graduation_load',
        ),
        migrations.RemoveField(
            model_name='program',
            name='specialization_entry_term',
        ),
        migrations.RemoveField(
            model_name='program',
            name='specialization_entry_year',
        ),
    ]
