# Generated by Django 5.2.7 on 2025-11-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkUploadPrograms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='bulk_uploads/')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('total_records', models.IntegerField(default=0)),
                ('processed_records', models.IntegerField(default=0)),
                ('success_records', models.IntegerField(default=0)),
                ('failed_records', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
