# Generated by Django 5.2.7 on 2026-05-11 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0003_program_academic_metadata'),
        ('Programs', '0003_program_calendar_type_program_has_specialization_and_more'),
    ]

    operations = [
    ]
