# Generated by Django 5.2.5 on 2026-05-12 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Programs", "0003_program_academic_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="curriculum_mode",
            field=models.CharField(
                choices=[
                    ("master", "Curriculum master"),
                    ("inherited", "Inherited curriculum"),
                    ("forked", "Forked curriculum"),
                ],
                default="master",
                help_text="master: owns curriculum; inherited: reads versions from curriculum_source_program; forked: local copy after fork.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="curriculum_source_program",
            field=models.ForeignKey(
                blank=True,
                help_text="Master programme row when curriculum_mode is inherited.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="curriculum_dependent_programs",
                to="Programs.program",
            ),
        ),
        migrations.AddField(
            model_name="programcurriculumversion",
            name="is_local_fork",
            field=models.BooleanField(
                default=False,
                help_text="True when this version is a campus-local fork of an inherited version.",
            ),
        ),
        migrations.AddField(
            model_name="programcurriculumversion",
            name="origin_version",
            field=models.ForeignKey(
                blank=True,
                help_text="Source curriculum version when this row was forked from a master.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_versions",
                to="Programs.programcurriculumversion",
            ),
        ),
    ]
