# Generated by Django 5.2.7 on 2025-11-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0003_bulkuploadprograms'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='code',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
