# Generated by Django 5.2.7 on 2025-11-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0004_program_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='duration_years',
            new_name='max_years',
        ),
        migrations.RemoveField(
            model_name='program',
            name='application_fee',
        ),
        migrations.AddField(
            model_name='program',
            name='min_years',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
