# Generated by Django 5.2.7 on 2026-05-14 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0004_merge_20260512_0115'),
        ('Programs', '0004_program_curriculum_inheritance'),
    ]

    operations = [
    ]
