# Generated by Django 5.2.5 on 2026-05-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Programs", "0005_merge_20260514_2128"),
    ]

    operations = [
        migrations.AddField(
            model_name="programbatch",
            name="offer_end_date",
            field=models.DateField(
                blank=True,
                help_text="Last day offers stay active for this cohort; null means no fixed end.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="programbatch",
            name="offer_start_date",
            field=models.DateField(
                blank=True,
                help_text="First day this academic cohort is open for admission/placement offers (same idea as admissions intake offer_start_date).",
                null=True,
            ),
        ),
    ]
