# Generated by Django 5.2.7 on 2025-11-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0005_rename_duration_years_program_max_years_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='short_form',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
