# Generated by Django 5.2.7 on 2025-11-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0006_program_short_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkuploadprograms',
            name='error_log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
