# Generated by Django 5.2.7 on 2026-05-15 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0005_merge_20260515_0209'),
        ('Programs', '0006_programbatch_offer_dates'),
    ]

    operations = [
    ]
