# Generated by Django 5.2.5 on 2026-05-15 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Programs", "0005_merge_20260515_0209"),
        ("Programs", "0006_programbatch_offer_dates"),
    ]

    operations = []
