# Generated by Django 5.2.7 on 2026-03-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0007_alter_bulkuploadprograms_error_log'),
        ('accounts', '0013_alter_user_is_applicant'),
        ('admissions', '0034_alter_admittedstudent_admitted_batch'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['code'], name='Programs_pr_code_5998d9_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['name'], name='Programs_pr_name_8ea6f8_idx'),
        ),
    ]
