# Generated by Django 5.2.7 on 2026-03-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0008_program_programs_pr_code_5998d9_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='code',
            field=models.CharField(max_length=40),
        ),
    ]
