# Generated by Django 5.2.7 on 2026-04-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Programs", "0009_alter_program_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="calendar_type",
            field=models.CharField(default="semester", max_length=20),
        ),
        migrations.AddField(
            model_name="program",
            name="has_specialization",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="program",
            name="minimum_graduation_load",
            field=models.DecimalField(decimal_places=1, default=120, max_digits=6),
        ),
        migrations.AddField(
            model_name="program",
            name="specialization_entry_term",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="specialization_entry_year",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
