# Generated by Django 5.2.5 on 2026-05-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Programs", "0010_timetable_ndejje_rules"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="venue",
            options={
                "ordering": ["campus__name", "building", "name"],
                "verbose_name": "Venue",
                "verbose_name_plural": "Venues",
            },
        ),
        migrations.AlterField(
            model_name="venue",
            name="name",
            field=models.CharField(help_text="e.g. Lecture Theatre 1", max_length=120),
        ),
    ]
