# Generated by Django 5.2.7 on 2026-04-29 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Programs", "0010_program_calendar_type_program_has_specialization_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="program",
            name="calendar_type",
        ),
        migrations.RemoveField(
            model_name="program",
            name="has_specialization",
        ),
        migrations.RemoveField(
            model_name="program",
            name="minimum_graduation_load",
        ),
        migrations.RemoveField(
            model_name="program",
            name="specialization_entry_term",
        ),
        migrations.RemoveField(
            model_name="program",
            name="specialization_entry_year",
        ),
    ]
