# Generated by Django 5.2.7 on 2026-06-05 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0008_merge_20260515_1550'),
        ('Programs', '0011_alter_venue_options_alter_venue_name'),
    ]

    operations = [
    ]
