# Generated by Django 5.2.5 on 2026-05-02 15:07

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Programs", "0011_remove_program_calendar_type_and_more"),
        ("admissions", "0052_application_add_source_columns"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseCatalogUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique catalog code (e.g. CS101).",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "credit_units",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Credit weight (e.g. 3.0).",
                        max_digits=5,
                    ),
                ),
                (
                    "lecture_hours",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Scheduled lecture hours (optional; used for contact total).",
                        null=True,
                    ),
                ),
                (
                    "practical_hours",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "tutorial_hours",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "contact_hours",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Total contact hours; left blank to auto-sum L+P+T on save.",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Course catalog unit",
                "verbose_name_plural": "Course catalog units",
                "ordering": ["code", "title"],
            },
        ),
        migrations.AddField(
            model_name="program",
            name="calendar_type",
            field=models.CharField(
                choices=[("semester", "Semester"), ("trimester", "Trimester")],
                default="semester",
                help_text="Academic calendar structure: semester (2 terms/year) or trimester (3 terms/year).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="has_specialization",
            field=models.BooleanField(
                default=False,
                help_text="Set to True if this programme branches into specialization tracks.",
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="minimum_graduation_load",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Minimum total credit units a student must accumulate to graduate from this programme.",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="specialization_entry_term",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Term within specialization_entry_year when the choice is required (e.g. 1 for the first term of Year 3).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="specialization_entry_year",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Year of study when students must choose a specialization (e.g. 3 for Year 3). Only relevant when has_specialization is True.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ProgramCurriculumVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculum_versions",
                        to="Programs.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Program Curriculum Version",
                "verbose_name_plural": "Program Curriculum Versions",
                "ordering": ["-is_default", "name", "-created_at"],
                "unique_together": {("program", "name")},
            },
        ),
        migrations.CreateModel(
            name="ProgramCurriculumLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year_of_study",
                    models.PositiveSmallIntegerField(
                        help_text="Academic year within the programme (1-based, e.g. 1, 2, 3)."
                    ),
                ),
                (
                    "term_number",
                    models.PositiveSmallIntegerField(
                        help_text="Term within the year. Valid values depend on the programme calendar: 1–2 for semester, 1–3 for trimester."
                    ),
                ),
                (
                    "course_type",
                    models.CharField(
                        choices=[("mandatory", "Mandatory"), ("elective", "Elective")],
                        default="mandatory",
                        max_length=20,
                    ),
                ),
                (
                    "elective_group",
                    models.CharField(
                        blank=True,
                        help_text="Groups electives for selection rules (e.g. 'Group A'). Null for mandatory courses.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        blank=True,
                        help_text="Reserved for future specialization/track filtering.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Display order within a year/semester block.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "catalog_course",
                    models.ForeignKey(
                        help_text="Catalogue entry being mapped into this programme slot.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="curriculum_lines",
                        to="Programs.coursecatalogunit",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculum_lines",
                        to="Programs.program",
                    ),
                ),
                (
                    "curriculum_version",
                    models.ForeignKey(
                        help_text="Curriculum version this line belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="Programs.programcurriculumversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Program Curriculum Line",
                "verbose_name_plural": "Program Curriculum Lines",
                "ordering": [
                    "year_of_study",
                    "term_number",
                    "sort_order",
                    "catalog_course__code",
                ],
            },
        ),
        migrations.CreateModel(
            name="ProgramBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Year 1, Year 2, Level 3", max_length=100
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Cohort year label (e.g. 2024/2025).",
                        max_length=50,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_batches",
                        to="Programs.program",
                    ),
                ),
                (
                    "curriculum_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="Curriculum version used by this cohort/batch. If blank, fallback logic resolves the programme default.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="program_batches",
                        to="Programs.programcurriculumversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Program Batch",
                "verbose_name_plural": "Program Batches",
                "ordering": ["-start_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProgramSpecialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Track name, e.g. 'Accounting', 'Marketing'. Must be unique per programme.",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "program",
                    models.ForeignKey(
                        help_text="The programme this track belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specializations",
                        to="Programs.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Program Specialization",
                "verbose_name_plural": "Program Specializations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Semester 1, Year 1 Sem 1", max_length=100
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Absolute semester sequence number within this batch.",
                    ),
                ),
                (
                    "year_of_study",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Academic year this semester belongs to (1-based). Aligns with ProgramCurriculumLine.year_of_study. Required to use curriculum suggestions.",
                        null=True,
                    ),
                ),
                (
                    "term_number",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Term within the year (1–2 for semester, 1–3 for trimester). Aligns with ProgramCurriculumLine.term_number.",
                        null=True,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "program_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semesters",
                        to="Programs.programbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["program_batch", "order", "start_date"],
            },
        ),
        migrations.CreateModel(
            name="CourseUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=50)),
                (
                    "credit_units",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "catalog_unit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional link to the shared catalog row; leave empty for legacy/offline entries.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduled_offerings",
                        to="Programs.coursecatalogunit",
                    ),
                ),
                (
                    "lecturers",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Staff assigned to teach this course unit",
                        related_name="course_units",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_units",
                        to="Programs.programbatch",
                    ),
                ),
                (
                    "curriculum_line",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional link to the curriculum blueprint this operational course was created from. Set this to make the course traceable to the programme curriculum.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offered_course_units",
                        to="Programs.programcurriculumline",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_units",
                        to="Programs.semester",
                    ),
                ),
            ],
            options={
                "ordering": ["code", "name"],
            },
        ),
        migrations.CreateModel(
            name="StudentCourseUnitEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrollment_date", models.DateTimeField(auto_now_add=True)),
                (
                    "registration_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date when student registered for this course",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enrolled", "Enrolled"),
                            ("completed", "Completed"),
                            ("withdrawn", "Withdrawn"),
                            ("failed", "Failed"),
                        ],
                        default="enrolled",
                        max_length=20,
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        help_text="Final grade if completed",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("self_registered", "Self Registered"),
                            ("admin_assigned", "Admin Assigned"),
                            ("transferred", "Transferred Credit"),
                            ("exempted", "Exempted"),
                        ],
                        default="self_registered",
                        help_text="How this enrollment came to exist. 'self_registered' = student registered via portal. 'admin_assigned' = admin enrolled the student directly. 'transferred' = credit recognised from another institution. 'exempted' = course waived by faculty decision.",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_enrollments",
                        to="Programs.courseunit",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_unit_enrollments",
                        to="admissions.admittedstudent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Course Unit Enrollment",
                "verbose_name_plural": "Student Course Unit Enrollments",
                "ordering": ["-enrollment_date"],
            },
        ),
        migrations.CreateModel(
            name="StudentProgrammeEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_year_of_study",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="The year of study the student actually started at. Set once at enrollment and never changed. Differs from current_year_of_study for advanced-entry / transfer students.",
                        null=True,
                    ),
                ),
                (
                    "entry_term_number",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="The term the student actually started at (e.g. 2 for January intake). Set once at enrollment and never changed.",
                        null=True,
                    ),
                ),
                (
                    "current_year_of_study",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Student's current academic year (1-based). Updated on progression.",
                    ),
                ),
                (
                    "current_term_number",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Student's current term within the year. Updated on progression.",
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        blank=True,
                        help_text="Selected track/specialization for programmes that branch (e.g. Accounting, Management, Marketing).",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Commitment Fee"),
                            ("enrolled", "Enrolled"),
                            ("suspended", "Suspended"),
                            ("completed", "Completed"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "enrolled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set automatically when status transitions to 'enrolled'.",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "curriculum_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="Pinned curriculum version for this student. Once set, expected/registration courses resolve from this version.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_enrollments",
                        to="Programs.programcurriculumversion",
                    ),
                ),
                (
                    "enrolled_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who confirmed the commitment fee and activated enrollment.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrolled_students",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        help_text="Must match program_batch.program.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_enrollments",
                        to="Programs.program",
                    ),
                ),
                (
                    "program_batch",
                    models.ForeignKey(
                        help_text="The academic cohort the student is placed in.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_enrollments",
                        to="Programs.programbatch",
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        help_text="Each admitted student has at most one academic enrollment record.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programme_enrollment",
                        to="admissions.admittedstudent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Programme Enrollment",
                "verbose_name_plural": "Student Programme Enrollments",
                "ordering": ["-enrolled_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentCurriculumOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "override_type",
                    models.CharField(
                        choices=[
                            ("exempted", "Exempted"),
                            ("transferred", "Transferred Credit"),
                            ("deferred", "Deferred"),
                            ("backlog", "Backlog"),
                            ("substituted", "Substituted"),
                        ],
                        help_text="exempted = waived entirely. transferred = credit from another institution. deferred = postponed to a later term. backlog = must be taken alongside a later-term cohort. substituted = another line satisfies this one.",
                        max_length=20,
                    ),
                ),
                (
                    "effective_year_of_study",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="When should this student actually take this course? Required for deferred and backlog types. Null means: use the blueprint year.",
                        null=True,
                    ),
                ),
                (
                    "effective_term_number",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Term within effective_year_of_study. Required alongside effective_year_of_study.",
                        null=True,
                    ),
                ),
                (
                    "transferred_grade",
                    models.CharField(
                        blank=True,
                        help_text="Grade awarded from the transferring institution (for transferred type).",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "transferred_institution",
                    models.CharField(
                        blank=True,
                        help_text="Name of the institution from which the credit was transferred.",
                        max_length=200,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Faculty decision reference, reason, or supporting note.",
                    ),
                ),
                ("decided_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "curriculum_line",
                    models.ForeignKey(
                        help_text="The blueprint line being overridden for this student.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_overrides",
                        to="Programs.programcurriculumline",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member who created this override.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="curriculum_override_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "substituted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The curriculum line that satisfies this one (for substituted type).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="substitutes_for",
                        to="Programs.programcurriculumline",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        help_text="The academic enrollment this override belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculum_overrides",
                        to="Programs.studentprogrammeenrollment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Curriculum Override",
                "verbose_name_plural": "Student Curriculum Overrides",
                "ordering": [
                    "enrollment",
                    "curriculum_line__year_of_study",
                    "curriculum_line__term_number",
                ],
            },
        ),
        migrations.CreateModel(
            name="StudentSemesterProgression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("detained", "Detained"),
                            ("promoted", "Promoted"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("enrollment_date", models.DateTimeField(auto_now_add=True)),
                ("completion_date", models.DateTimeField(blank=True, null=True)),
                ("promotion_date", models.DateTimeField(blank=True, null=True)),
                ("detained_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "program_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_progressions",
                        to="Programs.programbatch",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_progressions",
                        to="Programs.semester",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semester_progressions",
                        to="admissions.admittedstudent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Semester Progression",
                "verbose_name_plural": "Student Semester Progressions",
                "ordering": ["-enrollment_date"],
            },
        ),
        migrations.AddConstraint(
            model_name="programcurriculumline",
            constraint=models.UniqueConstraint(
                fields=(
                    "curriculum_version",
                    "catalog_course",
                    "year_of_study",
                    "term_number",
                ),
                name="unique_curriculum_slot",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="programbatch",
            unique_together={("program", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="programspecialization",
            unique_together={("program", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="semester",
            unique_together={("program_batch", "order")},
        ),
        migrations.AlterUniqueTogether(
            name="courseunit",
            unique_together={("code", "semester")},
        ),
        migrations.AlterUniqueTogether(
            name="studentcourseunitenrollment",
            unique_together={("student", "course_unit")},
        ),
        migrations.AddConstraint(
            model_name="studentcurriculumoverride",
            constraint=models.UniqueConstraint(
                fields=("enrollment", "curriculum_line"),
                name="unique_student_curriculum_override",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentsemesterprogression",
            unique_together={("student", "semester")},
        ),
    ]
