# Generated by Django 5.2.7 on 2026-06-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0012_merge_20260605_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='is_hec',
            field=models.BooleanField(default=False),
        ),
    ]
