# Generated by Django 5.2.5 on 2026-07-08 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Programs", "0014_timetablesession_session_date"),
        ("admissions", "0047_application_applicant_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LectureAttendanceSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_date", models.DateField()),
                (
                    "venue_label",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_sessions",
                        to="Programs.courseunit",
                    ),
                ),
                (
                    "taken_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lecture_attendance_sessions_taken",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "timetable_session",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional link when a published timetable slot matches this date.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_sessions",
                        to="Programs.timetablesession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lecture attendance session",
                "verbose_name_plural": "Lecture attendance sessions",
                "ordering": ["-session_date", "-id"],
                "permissions": [
                    ("take_lecture_attendance", "Can take lecture attendance"),
                    (
                        "manage_faculty_lecture_attendance",
                        "Can manage faculty lecture attendance",
                    ),
                ],
                "unique_together": {("course_unit", "session_date")},
            },
        ),
        migrations.CreateModel(
            name="LectureAttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("excused", "Excused"),
                        ],
                        default="absent",
                        max_length=20,
                    ),
                ),
                ("remark", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecture_attendance_records",
                        to="admissions.admittedstudent",
                    ),
                ),
                (
                    "attendance_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="Programs.lectureattendancesession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lecture attendance record",
                "verbose_name_plural": "Lecture attendance records",
                "ordering": ["student__reg_no", "student__student_id"],
                "unique_together": {("attendance_session", "student")},
            },
        ),
    ]
