# Generated by Django 5.2.5 on 2026-07-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Programs", "0015_lecture_attendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="lectureattendancerecord",
            name="checked_in_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lectureattendancerecord",
            name="marked_via",
            field=models.CharField(
                blank=True,
                choices=[
                    ("lecturer", "Lecturer"),
                    ("student", "Student self-check-in"),
                    ("admin", "Faculty / admin"),
                    ("paper", "Paper register"),
                ],
                default="lecturer",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lectureattendancesession",
            name="check_in_closed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the lecturer manually closed student self-check-in (if earlier than closes_at).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lectureattendancesession",
            name="check_in_closes_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When student self-check-in closes. Lecturer may still edit marks after this.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lectureattendancesession",
            name="check_in_duration_minutes",
            field=models.PositiveSmallIntegerField(
                default=30,
                help_text="Planned self-check-in window length (minutes). Recommended 20–30 for large classes.",
            ),
        ),
        migrations.AddField(
            model_name="lectureattendancesession",
            name="check_in_opened_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the lecturer opened student self-check-in for this class.",
                null=True,
            ),
        ),
    ]
