# Generated by Django 5.2.5 on 2026-07-10 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Programs", "0017_attendance_check_in_qr_token"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="lectureattendancesession",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="lectureattendancesession",
            name="timetable_session",
            field=models.ForeignKey(
                blank=True,
                help_text="Timetable slot for this meeting (required for multi-slot same-day classes).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_sessions",
                to="Programs.timetablesession",
            ),
        ),
        migrations.AddConstraint(
            model_name="lectureattendancesession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("timetable_session__isnull", False)),
                fields=("course_unit", "session_date", "timetable_session"),
                name="uniq_lecture_att_course_date_slot",
            ),
        ),
        migrations.AddConstraint(
            model_name="lectureattendancesession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("timetable_session__isnull", True)),
                fields=("course_unit", "session_date"),
                name="uniq_lecture_att_course_date_noslot",
            ),
        ),
    ]
