# Generated by Django 5.2.5 on 2026-07-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Programs", "0020_alter_lectureattendancerecord_marked_via"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentcourseunitenrollment",
            name="registration_kind",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("retake", "Retake"),
                    ("missed", "Missed paper"),
                ],
                db_index=True,
                default="normal",
                help_text="normal = first attempt; retake/missed = next-academic-year sitting of a prior paper.",
                max_length=16,
            ),
        ),
    ]
