# Generated by Django 5.2.7 on 2026-07-31 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0020_alter_lectureattendancerecord_marked_via'),
        ('Programs', '0025_courseunitsectionlecturer'),
    ]

    operations = [
    ]
