# Generated by Django 5.2.7 on 2026-08-05 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0026_merge_retake_and_teaching_sections'),
        ('Programs', '0027_studentcourseunitenrollment_registration_kind'),
    ]

    operations = [
    ]
