# Generated by Django 5.2.7 on 2026-08-10 09:17

import django.db.models.deletion
from django.apps import apps as django_apps
from django.conf import settings
from django.contrib.auth.management import create_permissions
from django.contrib.contenttypes.management import create_contenttypes
from django.db import migrations, models


def seed_study_group_perms(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    app_config = django_apps.get_app_config("Programs")
    create_contenttypes(app_config, verbosity=0, interactive=False, using=db_alias)
    create_permissions(app_config, verbosity=0, interactive=False, using=db_alias)
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    from admissions.faculty_admin_role_setup import seed_faculty_admin_role
    from admissions.faculty_dean_role_setup import seed_faculty_dean_role

    seed_faculty_admin_role(Group, Permission)
    seed_faculty_dean_role(Group, Permission)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("Programs", "0028_merge_20260805_2139"),
        ("accounts", "0048_role_capability_matrix"),
        ("admissions", "0061_temporary_access_pass_bursar_approval"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "code",
                    models.CharField(
                        help_text="Short code unique within the faculty (e.g. ENG-LAB-A).",
                        max_length=40,
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional label e.g. 2025/2026.",
                        max_length=25,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campus",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="study_groups",
                        to="accounts.campus",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="study_groups_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_groups",
                        to="admissions.faculty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Study group",
                "verbose_name_plural": "Study groups",
                "ordering": ["faculty__name", "name"],
                "permissions": [
                    ("manage_study_groups", "Can manage cross-programme study groups"),
                    ("view_study_groups", "Can view cross-programme study groups"),
                ],
            },
        ),
        migrations.CreateModel(
            name="StudyGroupMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="study_group_memberships_added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="Programs.studygroup",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_group_memberships",
                        to="admissions.admittedstudent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Study group membership",
                "verbose_name_plural": "Study group memberships",
                "ordering": ["group_id", "student_id"],
            },
        ),
        migrations.AddConstraint(
            model_name="studygroup",
            constraint=models.UniqueConstraint(
                fields=("faculty", "code"), name="uniq_studygroup_faculty_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="studygroupmembership",
            constraint=models.UniqueConstraint(
                fields=("group", "student"), name="uniq_studygroup_membership"
            ),
        ),
        migrations.RunPython(seed_study_group_perms, noop),
    ]
