# Generated by Django 5.2.5 on 2026-08-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Programs", "0029_study_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="teachingsection",
            name="is_shared",
            field=models.BooleanField(
                default=False,
                help_text="When true, students from the owning batch and linked_batches may be assigned to this section for shared teaching/timetable.",
            ),
        ),
        migrations.AddField(
            model_name="teachingsection",
            name="linked_batches",
            field=models.ManyToManyField(
                blank=True,
                help_text="Additional academic cohorts that may use this section when is_shared is true (same faculty as the owning batch).",
                related_name="linked_shared_sections",
                to="Programs.programbatch",
            ),
        ),
    ]
