# Generated by Django 5.2.5 on 2026-08-10 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Programs", "0030_teaching_section_shared_batches"),
    ]

    operations = [
        # Delete membership first (FK to StudyGroup). Avoid RemoveField on SQLite
        # — remaking the table breaks UniqueConstraint that still references
        # fields being dropped.
        migrations.DeleteModel(
            name="StudyGroupMembership",
        ),
        migrations.DeleteModel(
            name="StudyGroup",
        ),
    ]
