# Generated by Django 5.2.7 on 2026-08-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0032_timetablesession_start_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectureattendancerecord',
            name='marked_via',
            field=models.CharField(blank=True, choices=[('lecturer', 'Lecturer'), ('student', 'Student self-check-in'), ('admin', 'Faculty / admin'), ('paper', 'Paper register'), ('qr', 'Attendance code'), ('lms', 'LMS / Moodle')], default='lecturer', max_length=20),
        ),
    ]
