# Generated by Django 5.2.7 on 2026-08-21 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Programs", "0034_program_department"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="teachingsection",
            name="max_capacity",
            field=models.PositiveIntegerField(
                default=120,
                help_text="Teaching capacity warning/limit when moving students (0 = unlimited). The default MAIN section is always unlimited.",
            ),
        ),
        migrations.CreateModel(
            name="SharedTeachingOffering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Canonical course code shown on LMS / exam papers (e.g. BCS 1101).",
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "academic_year_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Academic year label, e.g. "2026/2027". Not tied to one programme semester PK.',
                        max_length=32,
                    ),
                ),
                (
                    "year_of_study",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Optional curriculum year (1-based).",
                        null=True,
                    ),
                ),
                (
                    "term_number",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Optional term within the year (1–2 semester, 1–3 trimester).",
                        null=True,
                    ),
                ),
                (
                    "exam_paper_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional paper / sitting code printed on scripts (defaults to moodle idnumber).",
                        max_length=64,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "catalog_unit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional link to the shared catalog definition.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shared_teachings",
                        to="Programs.coursecatalogunit",
                    ),
                ),
                (
                    "lecturers",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Staff teaching this shared class (may also be on linked CourseUnits).",
                        related_name="shared_teaching_offerings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Shared teaching offering",
                "verbose_name_plural": "Shared teaching offerings",
                "ordering": ["code", "academic_year_label", "term_number", "id"],
            },
        ),
        migrations.AddField(
            model_name="courseunit",
            name="shared_teaching_offering",
            field=models.ForeignKey(
                blank=True,
                help_text="When set, this programme offering shares LMS course, exam sitting, and marks entry with other CourseUnits linked to the same SharedTeachingOffering.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="course_units",
                to="Programs.sharedteachingoffering",
            ),
        ),
        migrations.AddIndex(
            model_name="sharedteachingoffering",
            index=models.Index(
                fields=["code", "academic_year_label", "term_number"],
                name="Programs_sh_code_c9fdd7_idx",
            ),
        ),
    ]
