# Generated by Django 5.2.7 on 2026-08-24 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0037_curriculum_slot_includes_specialization'),
        ('admissions', '0069_exemption_review_stages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='faculty',
            field=models.ForeignKey(blank=True, help_text='Required on create/update via API. Nullable only for legacy rows.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='admissions.faculty'),
        ),
    ]
