# Generated by Django 5.2.5 on 2026-08-27 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Programs", "0038_alter_program_faculty"),
        ("admissions", "0070_exemption_line_stage_decisions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseUnitClassCoordinator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="class_coordinators_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "course_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_coordinators",
                        to="Programs.courseunit",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_coordinator_assignments",
                        to="admissions.admittedstudent",
                    ),
                ),
                (
                    "teaching_section",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional section scope. Null = whole course unit / cohort.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_coordinators",
                        to="Programs.teachingsection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course unit class coordinator",
                "verbose_name_plural": "Course unit class coordinators",
                "ordering": ["course_unit__code", "student__reg_no"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("teaching_section__isnull", True)),
                        fields=("course_unit", "student"),
                        name="programs_cu_class_coord_all_unique",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("teaching_section__isnull", False)),
                        fields=("course_unit", "teaching_section", "student"),
                        name="programs_cu_class_coord_section_unique",
                    ),
                ],
            },
        ),
    ]
