# Generated by Django 5.2.5 on 2026-09-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Programs", "0041_coursecatalogunit_cross_cutting"),
    ]

    operations = [
        migrations.AddField(
            model_name="lectureattendancesession",
            name="start_latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Device location of whoever opened student self-check-in (lecturer or class coordinator), captured fresh each time check-in opens. Only stored when the device reported a reasonably accurate fix — see start_location_accuracy_m. Used to keep self-check-in near the class.",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lectureattendancesession",
            name="start_location_accuracy_m",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Accuracy (metres) the browser reported for start_latitude/longitude.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lectureattendancesession",
            name="start_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
