# Generated by Django 5.2.7 on 2026-09-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Programs", "0042_lecture_attendance_start_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="modular_papers_per_session",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Modular programmes only: number of papers a session's tuition is divided across for per-paper billing (session tuition ÷ this = one paper's fee). Defaults to 6 when unset.",
                null=True,
            ),
        ),
    ]
