# Generated by Django 5.2.5 on 2026-07-07 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appraisal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("OBJECTIVES_SET", "Objectives Set"),
                            ("SELF_ASSESSMENT", "Self-Assessment In Progress"),
                            ("SELF_COMPLETED", "Self-Assessment Completed"),
                            ("SUPERVISOR_REVIEW", "Under Supervisor Review"),
                            ("HR_REVIEW", "HR Review"),
                            ("APPROVED", "Approved"),
                            ("PUBLISHED", "Published to Staff"),
                            ("ACKNOWLEDGED", "Acknowledged by Staff"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("highest_qualification", models.CharField(blank=True, max_length=200)),
                ("courses_in_progress", models.TextField(blank=True)),
                ("contract_expiry_date", models.DateField(blank=True, null=True)),
                (
                    "objectives_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average of all objective scores",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "behavioral_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average of behavioral competencies",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "performance_factors_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average of performance factors",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "overall_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="(Objectives + Behavioral + Performance) / 3",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "overall_rating",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EXCEPTIONAL", "Exceptional (5)"),
                            ("EXCELLENT", "Excellent (4)"),
                            ("SATISFACTORY", "Satisfactory (3)"),
                            ("UNSATISFACTORY", "Unsatisfactory (0-2)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("supervisor_overall_comment", models.TextField(blank=True)),
                ("hr_comments", models.TextField(blank=True)),
                ("staff_acknowledgment_comment", models.TextField(blank=True)),
                ("self_completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "supervisor_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("hr_approved_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-cycle__academic_year", "staff__staff_no"],
            },
        ),
        migrations.CreateModel(
            name="AppraisalCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(help_text="e.g., 2024/2025", max_length=20),
                ),
                ("period_from", models.DateField(help_text="Review period start date")),
                ("period_to", models.DateField(help_text="Review period end date")),
                (
                    "review_window_from",
                    models.DateField(help_text="When staff can start submitting"),
                ),
                ("review_window_to", models.DateField(help_text="Submission deadline")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNING", "Planning"),
                            ("OBJECTIVE_SETTING", "Objective Setting"),
                            ("ACTIVE", "Active"),
                            ("REVIEW_WINDOW", "Review Window Open"),
                            ("COMPLETED", "Completed"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="PLANNING",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Only one active cycle per campus at a time",
                    ),
                ),
            ],
            options={
                "ordering": ["-academic_year", "-period_from"],
            },
        ),
        migrations.CreateModel(
            name="AppraisalObjective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "individual_objective",
                    models.TextField(help_text="Individual objective"),
                ),
                (
                    "indicative_tasks",
                    models.TextField(help_text="Tasks to achieve the objective"),
                ),
                (
                    "target_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Target %",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "baseline_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Baseline %",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Weight out of 5",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "individual_score_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Staff's self-assessed score %",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "achievements",
                    models.TextField(
                        blank=True, help_text="Staff describes their achievements"
                    ),
                ),
                ("supervisor_comments", models.TextField(blank=True)),
                (
                    "agreed_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Final agreed score out of 5",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "action_required",
                    models.TextField(blank=True, help_text="Any action required"),
                ),
            ],
            options={
                "ordering": ["appraisal", "id"],
            },
        ),
        migrations.CreateModel(
            name="BehavioralCompetency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "competency",
                    models.CharField(
                        choices=[
                            ("GOD_FEARING", "God fearing"),
                            ("RESPECT", "Respect"),
                            ("INTEGRITY", "Integrity"),
                            ("TEAMWORK", "Teamwork"),
                            ("COMMITMENT", "Commitment"),
                            ("INNOVATIVENESS", "Innovativeness"),
                            ("EQUITY", "Equity"),
                            ("EXCELLENCE", "Excellence"),
                            ("ACCOUNTABILITY", "Accountability"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of the competency from NDU form"
                    ),
                ),
                (
                    "self_assessment",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "supervisor_assessment",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "agreed_assessment",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ["appraisal", "id"],
            },
        ),
        migrations.CreateModel(
            name="DepartmentalObjective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("objective", models.TextField(help_text="Department objective")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["org_unit", "strategic_objective"],
            },
        ),
        migrations.CreateModel(
            name="DevelopmentObjective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("objective", models.TextField(help_text="Development objective")),
                (
                    "how_to_achieve",
                    models.TextField(help_text="How to achieve this objective"),
                ),
                ("target_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("DEFERRED", "Deferred"),
                        ],
                        default="PLANNED",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["appraisal", "id"],
            },
        ),
        migrations.CreateModel(
            name="MidYearReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_date", models.DateField()),
                (
                    "objectives_progress",
                    models.TextField(help_text="Progress on annual objectives"),
                ),
                ("challenges_faced", models.TextField(blank=True)),
                ("support_needed", models.TextField(blank=True)),
                (
                    "mid_year_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("staff_comments", models.TextField(blank=True)),
                ("supervisor_comments", models.TextField(blank=True)),
                (
                    "revised_objectives",
                    models.TextField(
                        blank=True,
                        help_text="Any adjustments to objectives for second half",
                    ),
                ),
            ],
            options={
                "ordering": ["-review_date"],
            },
        ),
        migrations.CreateModel(
            name="PerformanceFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "factor",
                    models.CharField(
                        choices=[
                            ("PROFESSIONAL_COMPETENCE", "Professional Competence"),
                            ("QUALITY_OF_WORK", "Quality of Work"),
                            ("WORK_RELATIONSHIPS", "Work Relationships"),
                            ("LEADERSHIP_SKILLS", "Leadership Skills"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the performance factor"),
                ),
                (
                    "self_assessment",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "supervisor_assessment",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "agreed_assessment",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "is_applicable",
                    models.BooleanField(
                        default=True, help_text="Leadership Skills only for managers"
                    ),
                ),
                (
                    "number_supervised",
                    models.IntegerField(
                        blank=True,
                        help_text="For leadership skills - number of staff supervised",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["appraisal", "id"],
            },
        ),
        migrations.CreateModel(
            name="PerformanceImprovementPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED_IMPROVED", "Completed - Improved"),
                            ("COMPLETED_NOT_IMPROVED", "Completed - Not Improved"),
                            ("EXTENDED", "Extended"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=30,
                    ),
                ),
                (
                    "improvement_areas",
                    models.TextField(help_text="Specific areas that need improvement"),
                ),
                (
                    "improvement_targets",
                    models.TextField(
                        help_text="Specific, measurable targets to achieve"
                    ),
                ),
                (
                    "support_provided",
                    models.TextField(
                        blank=True, help_text="Training, mentoring, resources provided"
                    ),
                ),
                ("progress_notes", models.TextField(blank=True)),
                ("mid_pip_review_date", models.DateField(blank=True, null=True)),
                ("mid_pip_review_notes", models.TextField(blank=True)),
                ("final_assessment", models.TextField(blank=True)),
                (
                    "outcome_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="StrategicObjective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(help_text="e.g., SO5", max_length=10, unique=True),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
    ]
