# Generated by Django 5.2.5 on 2026-07-07 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0040_ar_data_clerk_role"),
        ("appraisal", "0001_initial"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appraisal",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appraisals",
                to="staff.staffprofile",
            ),
        ),
        migrations.AddField(
            model_name="appraisal",
            name="supervisor",
            field=models.ForeignKey(
                help_text="Manager/Supervisor conducting the review",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supervised_appraisals",
                to="staff.staffprofile",
            ),
        ),
        migrations.AddField(
            model_name="appraisalcycle",
            name="campus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appraisal_cycles",
                to="accounts.campus",
            ),
        ),
        migrations.AddField(
            model_name="appraisal",
            name="cycle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appraisals",
                to="appraisal.appraisalcycle",
            ),
        ),
        migrations.AddField(
            model_name="appraisalobjective",
            name="appraisal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="objectives",
                to="appraisal.appraisal",
            ),
        ),
        migrations.AddField(
            model_name="behavioralcompetency",
            name="appraisal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="behavioral_competencies",
                to="appraisal.appraisal",
            ),
        ),
        migrations.AddField(
            model_name="departmentalobjective",
            name="org_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departmental_objectives",
                to="staff.department",
            ),
        ),
        migrations.AddField(
            model_name="appraisalobjective",
            name="departmental_objective",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="appraisal.departmentalobjective",
            ),
        ),
        migrations.AddField(
            model_name="developmentobjective",
            name="appraisal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="development_objectives",
                to="appraisal.appraisal",
            ),
        ),
        migrations.AddField(
            model_name="midyearreview",
            name="appraisal",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mid_year_review",
                to="appraisal.appraisal",
            ),
        ),
        migrations.AddField(
            model_name="performancefactor",
            name="appraisal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="performance_factors",
                to="appraisal.appraisal",
            ),
        ),
        migrations.AddField(
            model_name="performanceimprovementplan",
            name="appraisal",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pip",
                to="appraisal.appraisal",
            ),
        ),
        migrations.AddField(
            model_name="departmentalobjective",
            name="strategic_objective",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departmental_objectives",
                to="appraisal.strategicobjective",
            ),
        ),
        migrations.AddField(
            model_name="appraisalobjective",
            name="strategic_objective",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="appraisal.strategicobjective",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appraisalcycle",
            unique_together={("campus", "academic_year")},
        ),
        migrations.AlterUniqueTogether(
            name="appraisal",
            unique_together={("cycle", "staff")},
        ),
        migrations.AlterUniqueTogether(
            name="behavioralcompetency",
            unique_together={("appraisal", "competency")},
        ),
        migrations.AlterUniqueTogether(
            name="performancefactor",
            unique_together={("appraisal", "factor")},
        ),
    ]
