# Generated by Django 5.2.5 on 2026-05-23 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admissions", "0027_academicyear"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GraduationCeremony",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "completion_date",
                    models.DateField(
                        help_text="Month/year of completion shown on documents."
                    ),
                ),
                (
                    "show_marks_on_transcript",
                    models.BooleanField(
                        default=True,
                        help_text="When true, transcripts printed for this ceremony include numeric marks.",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_graduation_ceremonies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Graduation ceremonies",
                "ordering": ["-completion_date", "name"],
                "permissions": [
                    (
                        "manage_ceremonies",
                        "Can manage graduation ceremonies and sessions",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="GraduationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="e.g. Day 1 — Business", max_length=200),
                ),
                ("graduation_date", models.DateField()),
                ("venue", models.CharField(blank=True, default="", max_length=200)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ceremony",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="graduation.graduationceremony",
                    ),
                ),
            ],
            options={
                "ordering": ["graduation_date", "name"],
                "permissions": [
                    ("assign_students", "Can assign students to graduation sessions")
                ],
            },
        ),
        migrations.CreateModel(
            name="GraduationAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cgpa_at_assignment",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "credit_units_at_assignment",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "award_class",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "enrollment_completed",
                    models.BooleanField(
                        default=False,
                        help_text="When true, programme enrollment was set to completed.",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graduation_assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graduation_assignments",
                        to="admissions.admittedstudent",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="graduation.graduationsession",
                    ),
                ),
            ],
            options={
                "ordering": ["session__graduation_date", "student__reg_no"],
                "permissions": [
                    ("view_qualified_lists", "Can view graduation qualified lists"),
                    ("view_graduation_lists", "Can view printable graduation lists"),
                ],
                "unique_together": {("session", "student")},
            },
        ),
    ]
