# Generated by Django 5.2.7 on 2026-05-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfferLetterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('file', models.FileField(upload_to='admission_template/')),
                ('file_url', models.URLField(blank=True, null=True)),
                ('file_type', models.CharField(default='docx', max_length=10)),
                ('field_positions', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='active')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('hall_of_residence', models.CharField(blank=True, choices=[('AKIIBUA', 'Akiibua'), ('NJUKI', 'Njuki'), ('MUTEESA', 'Muteesa'), ('KAKUNGULU', 'Kakungulu'), ('YOKANA', 'Yokana'), ('RANDOM', 'Assign Randomly')], max_length=20, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
