# Generated by Django 5.2.7 on 2025-11-10 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0010_application_study_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferLetterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('file', models.FileField(upload_to='admission_template/')),
                ('file_url', models.URLField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.application')),
            ],
        ),
    ]
