# Generated by Django 5.2.7 on 2026-05-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdmissionLetter', '0001_initial'),
        ('Programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerlettertemplate',
            name='programs',
            field=models.ManyToManyField(to='Programs.program'),
        ),
        migrations.AddIndex(
            model_name='offerlettertemplate',
            index=models.Index(fields=['status', 'uploaded_at'], name='AdmissionLe_status_002af0_idx'),
        ),
    ]
