# Generated by Django 5.2.7 on 2025-11-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionLetter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerlettertemplate',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
