# Generated by Django 5.2.7 on 2025-11-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionLetter', '0002_offerlettertemplate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerlettertemplate',
            name='status',
            field=models.CharField(default='active'),
        ),
    ]
