# Generated by Django 5.2.7 on 2026-05-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionLetter', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerlettertemplate',
            name='file_type',
            field=models.CharField(default='docx', max_length=100),
        ),
        migrations.AlterField(
            model_name='offerlettertemplate',
            name='hall_of_residence',
            field=models.CharField(blank=True, choices=[('AKIIBUA', 'Akiibua'), ('NJUKI', 'Njuki'), ('MUTEESA', 'Muteesa'), ('KAKUNGULU', 'Kakungulu'), ('YOKANA', 'Yokana'), ('RANDOM', 'Assign Randomly')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='offerlettertemplate',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
