# Generated by Django 5.2.5 on 2026-08-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdmissionLetter", "0003_alter_offerlettertemplate_file_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offerlettertemplate",
            name="hall_of_residence",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AKIIBUA", "Akiibua"),
                    ("NJUKI", "Njuki"),
                    ("MUTEESA", "Muteesa"),
                    ("KAKUNGULU", "Kakungulu"),
                    ("KAKUNGULU_ANNEX", "Kakungulu Annex"),
                    ("YOKANA", "Yokana"),
                    ("NOAHS_ARK", "Noah's Ark"),
                    ("WEST_BUGANDA", "West Buganda"),
                    ("WEST_BUGANDA_ANNEX", "West Buganda Annex"),
                    ("WEKISA", "Wekisa"),
                    ("VICTORIA_MWAKA", "Victoria Mwaka"),
                    ("LUWEERO", "Luweero"),
                    ("RANDOM", "Assign Randomly"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
