# Generated by Django 5.2.7 on 2025-11-10 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionLetter', '0003_alter_offerlettertemplate_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerlettertemplate',
            name='application',
        ),
    ]
