# Generated by Django 5.2.7 on 2025-11-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionLetter', '0004_remove_offerlettertemplate_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerlettertemplate',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offerlettertemplate',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
