# Generated by Django 5.2.7 on 2025-11-10 21:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionLetter', '0005_alter_offerlettertemplate_file_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerlettertemplate',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
