# Generated by Django 5.2.7 on 2025-11-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionLetter', '0006_offerlettertemplate_uploaded_at'),
        ('Programs', '0003_bulkuploadprograms'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerlettertemplate',
            name='programs',
            field=models.ManyToManyField(to='Programs.program'),
        ),
    ]
