# Generated by Django 5.2.7 on 2025-11-25 09:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionLetter', '0007_offerlettertemplate_programs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerlettertemplate',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='document'),
        ),
    ]
