# Generated by Django 5.2.7 on 2025-11-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionLetter', '0008_alter_offerlettertemplate_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerlettertemplate',
            name='file',
            field=models.FileField(upload_to='admission_template/'),
        ),
    ]
