# Generated by Django 5.2.7 on 2026-03-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionLetter', '0009_alter_offerlettertemplate_file'),
        ('Programs', '0007_alter_bulkuploadprograms_error_log'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='offerlettertemplate',
            index=models.Index(fields=['status', 'uploaded_at'], name='AdmissionLe_status_002af0_idx'),
        ),
    ]
