# Generated by Django 5.2.7 on 2026-03-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionLetter', '0010_offerlettertemplate_admissionle_status_002af0_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerlettertemplate',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
