# Generated by Django 5.2.5 on 2026-04-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdmissionLetter", "0011_alter_offerlettertemplate_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="offerlettertemplate",
            name="hall_of_residence",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AKIIBUA", "Akiibua"),
                    ("NJUKI", "Njuki"),
                    ("MUTEESA", "Muteesa"),
                    ("KAKUNGULU", "Kakungulu"),
                    ("YOKANA", "Yokana"),
                    ("RANDOM", "Assign Randomly"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="offerlettertemplate",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
