# Generated by Django 5.2.7 on 2026-05-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DraftApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=10, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('nin', models.CharField(blank=True, max_length=20, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('disabled', models.CharField(blank=True, max_length=5, null=True)),
                ('next_of_kin_name', models.CharField(blank=True, max_length=200, null=True)),
                ('next_of_kin_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('next_of_kin_relationship', models.CharField(blank=True, max_length=20, null=True)),
                ('olevel_data', models.JSONField(default=dict)),
                ('alevel_data', models.JSONField(default=dict)),
                ('additional_qualifications', models.JSONField(default=list)),
                ('draft_passport_photo', models.ImageField(blank=True, null=True, upload_to='drafts/passport/')),
                ('draft_olevel_doc', models.FileField(blank=True, null=True, upload_to='drafts/documents/')),
                ('draft_alevel_doc', models.FileField(blank=True, null=True, upload_to='drafts/documents/')),
                ('draft_other_doc', models.FileField(blank=True, null=True, upload_to='drafts/documents/')),
                ('status', models.CharField(default='draft', max_length=20)),
            ],
            options={
                'verbose_name': 'Draft Application',
                'verbose_name_plural': 'Draft Applications',
                'ordering': ['-updated_at'],
            },
        ),
    ]
