# Generated by Django 5.2.7 on 2026-05-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DraftApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('nin', models.CharField(blank=True, max_length=20, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('disabled', models.CharField(blank=True, max_length=5, null=True)),
                ('nextOfKinName', models.CharField(blank=True, max_length=200, null=True)),
                ('next_of_kin_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('next_of_kin_relationship', models.CharField(blank=True, max_length=20, null=True)),
                ('has_olevel', models.BooleanField(default=False)),
                ('has_alevel', models.BooleanField(default=False)),
                ('olevel_data', models.JSONField(default=dict)),
                ('alevel_data', models.JSONField(default=dict)),
                ('additional_qualifications', models.JSONField(blank=True, default=list, null=True)),
                ('application_fee_paid', models.BooleanField(default=False)),
                ('application_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('passport_photo', models.FileField(blank=True, null=True, upload_to='draft_documents/passport/')),
                ('olevel_document', models.FileField(blank=True, null=True, upload_to='draft_documents/olevel/')),
                ('alevel_document', models.FileField(blank=True, null=True, upload_to='draft_documents/alevel/')),
                ('other_documents', models.FileField(blank=True, null=True, upload_to='draft_documents/other/')),
                ('status', models.CharField(default='draft', max_length=20)),
            ],
            options={
                'verbose_name': 'Draft Application',
                'verbose_name_plural': 'Draft Applications',
                'ordering': ['-updated_at'],
            },
        ),
    ]
