# Generated by Django 5.2.7 on 2026-05-07 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Drafts', '0001_initial'),
        ('Programs', '0001_initial'),
        ('accounts', '0001_initial'),
        ('admissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='draftapplication',
            name='academic_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.academiclevel'),
        ),
        migrations.AddField(
            model_name='draftapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='draftapplication',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.batch'),
        ),
        migrations.AddField(
            model_name='draftapplication',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.campus'),
        ),
        migrations.AddField(
            model_name='draftapplication',
            name='programs',
            field=models.ManyToManyField(blank=True, to='Programs.program'),
        ),
        migrations.AddConstraint(
            model_name='draftapplication',
            constraint=models.UniqueConstraint(fields=('applicant', 'batch'), name='unique_draft_per_user_batch'),
        ),
    ]
