# Generated by Django 5.2.7 on 2026-04-23 00:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drafts', '0001_initial'),
        ('Programs', '0009_alter_program_code'),
        ('accounts', '0018_alter_systemsettings_id'),
        ('admissions', '0043_repair_application_missing_columns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='draftapplication',
            constraint=models.UniqueConstraint(fields=('applicant', 'batch'), name='unique_draft_per_user_batch'),
        ),
    ]
