# Generated by Django 5.2.7 on 2026-04-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drafts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftapplication',
            name='application_fee_paid',
            field=models.BooleanField(default=False),
        ),
    ]
