# Generated by Django 5.2.7 on 2026-05-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drafts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftapplication',
            name='next_of_kin_contact',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
