# Generated by Django 5.2.7 on 2026-04-23 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drafts', '0002_draftapplication_unique_draft_per_user_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftapplication',
            name='application_reference',
        ),
    ]
