# Generated by Django 5.2.7 on 2026-05-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drafts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftapplication',
            name='title',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
