# Generated by Django 5.2.7 on 2026-04-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drafts', '0002_draftapplication_application_fee_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftapplication',
            name='application_reference',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
