# Generated by Django 5.2.7 on 2026-04-23 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drafts', '0003_remove_draftapplication_application_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftapplication',
            name='application_reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
