# Generated by Django 5.2.7 on 2026-04-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drafts', '0003_draftapplication_application_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftapplication',
            name='additional_qualifications',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
