# Generated by Django 5.2.7 on 2026-04-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drafts', '0004_draftapplication_application_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftapplication',
            name='has_alevel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='draftapplication',
            name='has_olevel',
            field=models.BooleanField(default=False),
        ),
    ]
