# Generated by Django 5.2.7 on 2026-05-13 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drafts', '0003_alter_draftapplication_applicant'),
        ('Drafts', '0004_alter_draftapplication_next_of_kin_contact'),
    ]

    operations = [
    ]
