# Generated by Django 5.2.7 on 2026-04-17 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drafts', '0004_alter_draftapplication_additional_qualifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draftapplication',
            old_name='next_of_kin_name',
            new_name='nextOfKinName',
        ),
    ]
