# Generated by Django 5.2.7 on 2026-05-06 12:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drafts', '0004_alter_draftapplication_next_of_kin_contact'),
        ('Programs', '0002_initial'),
        ('accounts', '0001_initial'),
        ('admissions', '0003_alter_application_next_of_kin_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='draftapplication',
            old_name='next_of_kin_name',
            new_name='nextOfKinName',
        ),
        migrations.RemoveField(
            model_name='draftapplication',
            name='draft_alevel_doc',
        ),
        migrations.RemoveField(
            model_name='draftapplication',
            name='draft_olevel_doc',
        ),
        migrations.RemoveField(
            model_name='draftapplication',
            name='draft_other_doc',
        ),
        migrations.RemoveField(
            model_name='draftapplication',
            name='draft_passport_photo',
        ),
        migrations.AddField(
            model_name='draftapplication',
            name='alevel_document',
            field=models.FileField(blank=True, null=True, upload_to='draft_documents/alevel/'),
        ),
        migrations.AddField(
            model_name='draftapplication',
            name='application_fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='draftapplication',
            name='application_reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='draftapplication',
            name='has_alevel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='draftapplication',
            name='has_olevel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='draftapplication',
            name='olevel_document',
            field=models.FileField(blank=True, null=True, upload_to='draft_documents/olevel/'),
        ),
        migrations.AddField(
            model_name='draftapplication',
            name='other_documents',
            field=models.FileField(blank=True, null=True, upload_to='draft_documents/other/'),
        ),
        migrations.AddField(
            model_name='draftapplication',
            name='passport_photo',
            field=models.FileField(blank=True, null=True, upload_to='draft_documents/passport/'),
        ),
        migrations.AlterField(
            model_name='draftapplication',
            name='additional_qualifications',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='draftapplication',
            name='next_of_kin_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='draftapplication',
            constraint=models.UniqueConstraint(fields=('applicant', 'batch'), name='unique_draft_per_user_batch'),
        ),
    ]
