# Generated by Django 5.2.5 on 2026-04-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Drafts", "0005_draftapplication_has_alevel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftapplication",
            name="alevel_document",
            field=models.FileField(
                blank=True, null=True, upload_to="draft_documents/alevel/"
            ),
        ),
        migrations.AddField(
            model_name="draftapplication",
            name="olevel_document",
            field=models.FileField(
                blank=True, null=True, upload_to="draft_documents/olevel/"
            ),
        ),
        migrations.AddField(
            model_name="draftapplication",
            name="other_documents",
            field=models.FileField(
                blank=True, null=True, upload_to="draft_documents/other/"
            ),
        ),
        migrations.AddField(
            model_name="draftapplication",
            name="passport_photo",
            field=models.FileField(
                blank=True, null=True, upload_to="draft_documents/passport/"
            ),
        ),
    ]
