# Generated by Django 5.2.7 on 2026-05-13 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drafts', '0005_alter_draftapplication_applicant'),
        ('Drafts', '0005_merge_20260513_1634'),
    ]

    operations = [
    ]
