# Generated by Django 5.2.7 on 2026-05-13 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drafts', '0005_merge_20260513_1111'),
        ('Drafts', '0005_merge_20260513_1634'),
    ]

    operations = [
    ]
