# Generated by Django 5.2.7 on 2026-05-14 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drafts', '0006_merge_20260514_0211'),
    ]

    operations = [
    ]
