# Generated by Django 5.2.7 on 2026-05-13 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drafts', '0006_merge_20260513_2252'),
        ('Drafts', '0006_merge_20260514_0211'),
    ]

    operations = [
    ]
