# Generated by Django 5.2.5 on 2026-05-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Drafts", "0006_draftapplication_alevel_document_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="draftapplication",
            name="unique_draft_per_user_batch",
        ),
        migrations.RemoveField(
            model_name="draftapplication",
            name="alevel_document",
        ),
        migrations.RemoveField(
            model_name="draftapplication",
            name="application_fee_paid",
        ),
        migrations.RemoveField(
            model_name="draftapplication",
            name="application_reference",
        ),
        migrations.RemoveField(
            model_name="draftapplication",
            name="has_alevel",
        ),
        migrations.RemoveField(
            model_name="draftapplication",
            name="has_olevel",
        ),
        migrations.RemoveField(
            model_name="draftapplication",
            name="nextOfKinName",
        ),
        migrations.RemoveField(
            model_name="draftapplication",
            name="olevel_document",
        ),
        migrations.RemoveField(
            model_name="draftapplication",
            name="other_documents",
        ),
        migrations.RemoveField(
            model_name="draftapplication",
            name="passport_photo",
        ),
        migrations.AddField(
            model_name="draftapplication",
            name="draft_alevel_doc",
            field=models.FileField(
                blank=True, null=True, upload_to="drafts/documents/"
            ),
        ),
        migrations.AddField(
            model_name="draftapplication",
            name="draft_olevel_doc",
            field=models.FileField(
                blank=True, null=True, upload_to="drafts/documents/"
            ),
        ),
        migrations.AddField(
            model_name="draftapplication",
            name="draft_other_doc",
            field=models.FileField(
                blank=True, null=True, upload_to="drafts/documents/"
            ),
        ),
        migrations.AddField(
            model_name="draftapplication",
            name="draft_passport_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="drafts/passport/"
            ),
        ),
        migrations.AddField(
            model_name="draftapplication",
            name="next_of_kin_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="draftapplication",
            name="additional_qualifications",
            field=models.JSONField(default=list),
        ),
    ]
