# Generated by Django 5.2.7 on 2026-05-14 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drafts', '0007_merge_20260514_0253'),
        ('Drafts', '0007_merge_20260514_0333'),
    ]

    operations = [
    ]
