# Generated by Django 5.2.5 on 2026-05-14 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Drafts", "0003_alter_draftapplication_applicant"),
        ("Drafts", "0007_merge_20260514_0333"),
    ]

    operations = []
