# Generated by Django 5.2.7 on 2026-05-14 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drafts', '0008_merge_20260514_1600'),
        ('Programs', '0004_merge_20260512_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftapplication',
            name='programs',
        ),
        migrations.CreateModel(
            name='DraftProgramChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_order', models.PositiveIntegerField()),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_choices', to='Drafts.draftapplication')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Programs.program')),
            ],
            options={
                'ordering': ['choice_order'],
                'unique_together': {('draft', 'choice_order')},
            },
        ),
    ]
