# Generated by Django 5.2.7 on 2026-05-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drafts', '0009_remove_draftapplication_programs_draftprogramchoice'),
        ('Programs', '0004_merge_20260512_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftapplication',
            name='programs',
            field=models.ManyToManyField(blank=True, to='Programs.program'),
        ),
    ]
