# Generated by Django 5.2.7 on 2026-05-14 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drafts', '0008_merge_20260514_0341'),
        ('Drafts', '0010_draftapplication_programs'),
    ]

    operations = [
    ]
