# Generated by Django 5.2.7 on 2026-05-14 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drafts', '0011_merge_20260515_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftapplication',
            name='programs',
        ),
    ]
