# Generated by Django 5.2.7 on 2026-05-15 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drafts', '0012_remove_draftapplication_programs'),
    ]

    operations = [
    ]
