# Generated by Django 5.2.5 on 2026-05-15 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Drafts", "0008_merge_20260514_2128"),
        ("Drafts", "0012_remove_draftapplication_programs"),
    ]

    operations = []
