# Generated by Django 5.2.7 on 2026-05-14 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drafts', '0011_merge_20260515_0115'),
        ('Drafts', '0012_remove_draftapplication_programs'),
    ]

    operations = [
    ]
