# Generated by Django 5.2.7 on 2026-05-15 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drafts', '0008_merge_20260514_2128'),
        ('Drafts', '0013_merge_20260515_1516'),
    ]

    operations = [
    ]
