# Generated by Django 5.2.7 on 2026-05-15 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drafts', '0013_merge_20260515_1523'),
        ('Drafts', '0014_merge_20260515_1538'),
    ]

    operations = [
    ]
