# Generated by Django 5.2.7 on 2026-05-15 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drafts', '0013_merge_20260515_0232'),
        ('Drafts', '0015_merge_20260515_1550'),
    ]

    operations = [
    ]
