# Generated by Django 5.2.7 on 2026-05-15 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drafts', '0015_merge_20260515_1550'),
    ]

    operations = [
    ]
