# Generated by Django 5.2.7 on 2026-05-15 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drafts', '0016_merge_20260515_1612'),
    ]

    operations = [
    ]
