# Generated by Django 5.2.7 on 2026-05-15 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drafts', '0017_merge_20260515_1616'),
        ('Drafts', '0017_merge_20260515_1621'),
    ]

    operations = [
    ]
