# Generated by Django 5.2.7 on 2026-05-17 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drafts', '0017_merge_20260515_1621'),
    ]

    operations = [
    ]
