# Generated by Django 5.2.7 on 2026-05-17 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drafts', '0018_merge_20260516_0217'),
        ('Drafts', '0018_merge_20260517_1128'),
    ]

    operations = [
    ]
