# Generated by Django 5.2.7 on 2026-05-19 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drafts', '0003_alter_draftapplication_applicant'),
        ('Drafts', '0018_merge_20260517_1128'),
    ]

    operations = [
    ]
