# Generated by Django 5.2.7 on 2026-05-20 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drafts', '0019_merge_20260517_2133'),
        ('Drafts', '0019_merge_20260519_1423'),
    ]

    operations = [
    ]
