# Generated by Django 5.2.7 on 2026-05-22 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drafts', '0020_merge_20260520_1008'),
        ('Drafts', '0020_merge_20260522_0958'),
    ]

    operations = [
    ]
