# Generated by Django 5.2.7 on 2026-05-23 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drafts', '0021_merge_20260522_1034'),
        ('Drafts', '0021_merge_20260523_1427'),
    ]

    operations = [
    ]
