# Generated by Django 5.2.7 on 2026-05-27 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drafts', '0022_alter_draftapplication_applicant'),
        ('Drafts', '0022_merge_20260523_1454'),
    ]

    operations = [
    ]
