# Generated by Django 5.2.5 on 2026-06-18 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Drafts", "0022_alter_draftapplication_applicant"),
    ]

    operations = [
        migrations.CreateModel(
            name="DraftOtherDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="draft_documents/other/")),
                ("original_name", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="other_document_files",
                        to="Drafts.draftapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["uploaded_at", "id"],
            },
        ),
    ]
