# Generated by Django 5.2.7 on 2026-06-18 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drafts', '0023_draft_other_documents'),
        ('Drafts', '0023_merge_20260527_1609'),
    ]

    operations = [
    ]
