# Generated by Django 5.2.7 on 2026-06-29 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drafts', '0024_merge_20260619_0001'),
        ('Drafts', '0025_draftapplication_applicant_category'),
    ]

    operations = [
    ]
