# Generated by Django 5.2.7 on 2026-05-23 07:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Programs", "0011_alter_venue_options_alter_venue_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "ca_max",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("40"), max_digits=5
                    ),
                ),
                (
                    "exam_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.60"),
                        help_text="Exam contribution: final includes exam_mark × this (e.g. 0.60).",
                        max_digits=4,
                    ),
                ),
                (
                    "min_ca_to_sit_exam",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("17.5"), max_digits=5
                    ),
                ),
                (
                    "pass_mark",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("50"), max_digits=5
                    ),
                ),
                ("is_default", models.BooleanField(db_index=True, default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Assessment policy",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="GradeScale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CourseUnitResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ca_mark",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "exam_mark",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "final_mark",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("exam_sitting_allowed", models.BooleanField(default=False)),
                ("is_pass", models.BooleanField(blank=True, null=True)),
                (
                    "grade_letter",
                    models.CharField(blank=True, default="", max_length=5),
                ),
                (
                    "grade_point",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("remark", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enrollment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_result",
                        to="Programs.studentcourseunitenrollment",
                    ),
                ),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entered_course_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="results",
                        to="examinations.assessmentpolicy",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_course_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "permissions": [
                    ("enter_marks", "Can enter course marks (lecturer)"),
                    ("publish_results", "Can publish examination results"),
                    ("view_all_results", "Can view all examination results"),
                ],
            },
        ),
        migrations.CreateModel(
            name="GradeBand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("letter", models.CharField(max_length=5)),
                ("min_mark", models.DecimalField(decimal_places=1, max_digits=5)),
                ("max_mark", models.DecimalField(decimal_places=1, max_digits=5)),
                ("grade_point", models.DecimalField(decimal_places=1, max_digits=4)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "grade_scale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bands",
                        to="examinations.gradescale",
                    ),
                ),
            ],
            options={
                "ordering": ["-min_mark", "order"],
                "unique_together": {("grade_scale", "letter")},
            },
        ),
    ]
