# Generated by Django 5.2.7 on 2026-05-23 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Programs", "0011_alter_venue_options_alter_venue_name"),
        ("examinations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("regular", "Regular"),
                            ("retake", "Retake"),
                            ("supplementary", "Supplementary"),
                        ],
                        db_index=True,
                        default="regular",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("exam_date", models.DateField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "venue_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Free-text room if not using the venue register.",
                        max_length=200,
                    ),
                ),
                ("max_candidates", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="When true, students enrolled on this course can see the session.",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_sessions",
                        to="Programs.courseunit",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_exam_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exam_sessions",
                        to="Programs.venue",
                    ),
                ),
            ],
            options={
                "ordering": ["exam_date", "start_time", "id"],
                "permissions": [
                    (
                        "manage_exam_schedule",
                        "Can manage examination timetable and sittings",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ExamRetakeRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("admin_notes", models.TextField(blank=True, default="")),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_retake_registrations",
                        to="Programs.studentcourseunitenrollment",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_exam_retakes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exam_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retake_registrations",
                        to="examinations.examsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
                "permissions": [
                    ("manage_retakes", "Can approve and schedule examination retakes")
                ],
            },
        ),
    ]
