# Generated by Django 5.2.5 on 2026-05-23 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0027_academicyear"),
        ("examinations", "0006_assessmentpolicy_academic_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessmentpolicy",
            name="academic_level",
            field=models.ForeignKey(
                blank=True,
                help_text="When set, applies to all programmes at this level. Leave blank for global fallback.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assessment_policies",
                to="admissions.academiclevel",
            ),
        ),
    ]
