# Generated by Django 5.2.5 on 2026-05-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examinations", "0008_academic_level_grading_and_award_schemes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awardclassband",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="awardclassificationscheme",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
