# Generated by Django 5.2.5 on 2026-05-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examinations", "0010_examcardtoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examcardtoken",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="examcardtoken",
            name="verification_code",
            field=models.UUIDField(db_index=True, editable=False, unique=True),
        ),
    ]
