# Generated by Django 5.2.5 on 2026-07-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examinations", "0012_marksentrywindow"),
        ("staff", "0002_payscale"),
    ]

    operations = [
        migrations.AddField(
            model_name="examsession",
            name="invigilators",
            field=models.ManyToManyField(
                blank=True,
                help_text="Staff assigned to invigilate this sitting.",
                related_name="exam_sessions_invigilating",
                to="staff.staffprofile",
            ),
        ),
    ]
