# Generated by Django 5.2.5 on 2026-07-27 19:16

from django.db import migrations, models


def backfill_paper_outcome(apps, schema_editor):
    CourseUnitResult = apps.get_model("examinations", "CourseUnitResult")
    for result in CourseUnitResult.objects.filter(status="published").iterator():
        if result.is_pass is True:
            outcome = "pass"
        elif result.exam_mark is None and result.is_pass is not True:
            outcome = "missed"
        elif result.is_pass is False:
            outcome = "fail"
        else:
            outcome = ""
        if outcome and result.paper_outcome != outcome:
            result.paper_outcome = outcome
            result.save(update_fields=["paper_outcome"])


class Migration(migrations.Migration):

    dependencies = [
        ("examinations", "0013_examsession_invigilators"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseunitresult",
            name="paper_outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pass", "Pass"),
                    ("fail", "Fail"),
                    ("missed", "Missed paper"),
                ],
                db_index=True,
                default="",
                help_text="pass / fail / missed once published. Missed = no exam mark (did not sit).",
                max_length=16,
            ),
        ),
        migrations.RunPython(backfill_paper_outcome, migrations.RunPython.noop),
    ]
