# Generated by Django 5.2.5 on 2026-09-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examinations", "0014_retake_missed_paper_registration"),
    ]

    operations = [
        migrations.AddField(
            model_name="marksentrywindow",
            name="component",
            field=models.CharField(
                choices=[
                    ("ca", "CA only"),
                    ("exam", "Exam only"),
                    ("both", "CA + Exam"),
                ],
                default="both",
                help_text="Which mark(s) this window governs. CA is normally entered and locked before the exam sits; Exam only opens once results are in.",
                max_length=10,
            ),
        ),
    ]
