# Generated by Django 5.2.7 on 2026-09-24 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def grandfather_already_published(apps, schema_editor):
    """Results published before the Dean-approval gate existed shouldn't get
    blocked from being re-published (e.g. via unpublish -> publish) just
    because hod_status/dean_status default to 'pending' on this migration."""
    CourseUnitResult = apps.get_model("examinations", "CourseUnitResult")
    CourseUnitResult.objects.filter(status="published").update(
        hod_status="approved", dean_status="approved",
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("examinations", "0015_marks_window_component"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courseunitresult",
            options={
                "ordering": ["-updated_at"],
                "permissions": [
                    ("enter_marks", "Can enter course marks (lecturer)"),
                    ("publish_results", "Can publish examination results"),
                    ("view_all_results", "Can view all examination results"),
                    ("review_marks_hod", "Can review submitted marks (HOD stage)"),
                    ("review_marks_dean", "Can review submitted marks (Dean stage)"),
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="resultchangerequest",
            options={
                "ordering": ["-requested_at"],
                "permissions": [
                    (
                        "approve_result_changes",
                        "Can give final (AR) approval on post-publish result changes",
                    ),
                    (
                        "review_result_changes_hod",
                        "Can review post-publish result changes (HOD stage)",
                    ),
                    (
                        "review_result_changes_dean",
                        "Can review post-publish result changes (Dean stage)",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="courseunitresult",
            name="dean_notes",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="courseunitresult",
            name="dean_reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="courseunitresult",
            name="dean_reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dean_reviewed_course_results",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="courseunitresult",
            name="dean_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="courseunitresult",
            name="hod_notes",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="courseunitresult",
            name="hod_reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="courseunitresult",
            name="hod_reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hod_reviewed_course_results",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="courseunitresult",
            name="hod_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="courseunitresult",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="courseunitresult",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_course_results",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="resultchangerequest",
            name="dean_reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resultchangerequest",
            name="dean_reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dean_reviewed_result_change_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="resultchangerequest",
            name="dean_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="resultchangerequest",
            name="hod_reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resultchangerequest",
            name="hod_reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hod_reviewed_result_change_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="resultchangerequest",
            name="hod_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="resultchangerequest",
            name="supporting_document",
            field=models.FileField(
                blank=True,
                help_text="e.g. a re-marked script. Required at submission time (enforced in the view).",
                null=True,
                upload_to="result_change_documents/",
            ),
        ),
        migrations.AlterField(
            model_name="courseunitresult",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("verified", "Submitted"),
                    ("published", "Published"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="resultchangerequest",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Final (AR) stage reviewer -- HOD/Dean stages tracked separately below.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="result_change_requests_reviewed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(grandfather_already_published, noop_reverse),
    ]
